import {createMountTurnGait} from './mount-turn-r14.mjs';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {clone as cloneSkeleton} from './vendor/SkeletonUtils.js';
import {inventoryBinding,targetLockBinding} from './rpg-controls-r13.mjs?v=20261008-r14';

export const MOUNT_LIMITS=Object.freeze({maxAltitude:18,ascent:3,descent:2.5,flightSpeed:8,groundSpeed:6.1,walkSpeed:.618,slope:Math.tan(Math.PI/6),maxTilt:Math.PI/15,step:.15,groundTurnRate:1.25,groundMovingTurnRate:.8,flightTurnRate:2.8,turnStep:.065});
export const MOUNT_TYPES=Object.freeze({stag:{name:'苔冠鹿',file:'mosscrest_stag',idle:'idle',groundWidth:1.45,exit:1.65},gryphon:{name:'曙翼狮鹫',file:'dawnkite_gryphon',idle:'ground_idle',groundWidth:1.96,exit:2.65}});
export function mountBinding(state){const used=new Set([...(state.aliases??[]),...Object.values(state.baseBindings??{}),inventoryBinding(state),targetLockBinding(state)]);return ['KeyG','KeyZ','KeyC','KeyV','KeyX','KeyH','KeyN','KeyM','KeyJ'].find(k=>!used.has(k))??null;}
const contacts=[[-.4,.71],[.4,.71],[-.4,-.63],[.4,-.63]];
const contactNames=['contact_front_L','contact_front_R','contact_hind_L','contact_hind_R'];
const smooth=t=>{t=Math.max(0,Math.min(1,t));return t*t*(3-2*t);};

// All mutable riding state belongs here. Saved RPG state is only read through callbacks.
export async function createMountController({T,scene,hero,quality,height,getSolids,getQuest,getEnemies,isActive,isFootGrounded,worldLimit,onChange=()=>{},onNotice=()=>{},onRestore=()=>{}}){
 const rigs={},loads=[];
 for(const [id,type]of Object.entries(MOUNT_TYPES)){
  const path=`./assets/${type.file}-${quality}-r14.glb`,response=await fetch(new URL(path,import.meta.url));if(!response.ok)throw Error('Mount asset unavailable: '+path);
  const bytes=await response.arrayBuffer(),gltf=await new GLTFLoader().parseAsync(bytes,''),template=gltf.scene.getObjectByName(type.file+'_mount_root');if(!template)throw Error('Missing mount root: '+id);
  const root=cloneSkeleton(template),mixer=new T.AnimationMixer(root),actions=new Map();root.name=id+'_mount_r14';root.visible=false;scene.add(root);
  let triangles=0,meshes=0;const materials=[];root.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;o.material=o.material.clone();materials.push(o.material);o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;}});
  for(const clip of gltf.animations)actions.set(clip.name,mixer.clipAction(clip));
  for(const name of [type.idle,'walk','run',...(id==='gryphon'?['flap','glide']:[])])if(!actions.has(name))throw Error('Missing mount clip '+id+':'+name);
  const sockets=Object.fromEntries(['rider_seat','rider_foot_L','rider_foot_R','rein_grip_L','rein_grip_R',...contactNames].map(n=>{const o=root.getObjectByName(n);if(!o)throw Error('Missing mount socket '+n);return[n,o];}));
  actions.get(type.idle).play();mixer.update(0);root.updateWorldMatrix(true,true);const turn=createMountTurnGait({T,root,height});mixer.stopAllAction();const soles=[];root.traverse(o=>{if(!o.isSkinnedMesh)return;const a=o.geometry.attributes,seen=new Set();for(let i=0;i<a.position.count;i++){let best=null,weight=0;for(let lane=0;lane<4;lane++){const bone=o.skeleton.bones[a.skinIndex.getComponent(i,lane)],w=a.skinWeight.getComponent(i,lane);if(bone?.name.endsWith('_foot')&&w>weight){best=bone.name.replace(/_foot$/,'');weight=w;}}if(weight<.5)continue;const k=best+':'+[a.position.getX(i),a.position.getY(i),a.position.getZ(i)].map(v=>v.toFixed(5)).join(',');if(seen.has(k))continue;seen.add(k);soles.push({mesh:o,index:i,leg:best});}});if(!soles.length||soles.length>4096)throw Error('Mount sole sample budget invalid');rigs[id]={root,mixer,actions,sockets,materials,turn,soles,groundBlend:0,support:{minimum:0,correction:0,clearances:{}},clip:null,triangles,meshes};loads.push({id,path,bytes:bytes.byteLength,triangles,meshes,clips:[...actions.keys()]});
 }
 const player=hero.root.position,rest=new Map();for(const o of [hero.body,...hero.limbs,...hero.knees,...hero.elbows,...hero.ankles,hero.cape])rest.set(o,{position:o.position.clone(),quaternion:o.quaternion.clone()});
 const originalSwordVisible=hero.sword.visible,v=new T.Vector3(),v2=new T.Vector3(),seat=new T.Vector3(),quat=new T.Quaternion(),invYaw=new T.Quaternion(),bodyQ=new T.Quaternion(),leanQ=new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),.20),hipCenter=new T.Vector3(0,1.025,0),axisX=new T.Vector3(1,0,0),basis=new T.Quaternion();
 let disposed=false,lifecycleOpacity=1,cameraOpacity=1;
 let selected='stag',kind=null,phase='foot',age=0,heading=hero.root.rotation.y,speed=0,verticalSpeed=0,transition=null,lastReturn={x:player.x,z:player.z,heading},lastReason='',lastBlockedAt=-100,clock=0,landingSettled=0;
 const stats={summons:0,rides:0,dismounts:0,takeoffs:0,landings:0,blocked:0,steps:0};
 const activeRig=()=>rigs[kind];
 const owns=()=>phase!=='foot';
 const airborne=()=>['takeoff','flying','landing'].includes(phase);
 function fail(reason,code='blocked'){lastReason=reason;stats.blocked++;return {ok:false,reason,code};}
 function notify(reason){if(clock-lastBlockedAt>1.5){lastBlockedAt=clock;onNotice(reason);}}
 function change(next){if(next!=='riding')activeRig()?.turn.clearSupport();phase=next;age=0;speed=0;verticalSpeed=0;onChange(next);}
 function point(x,z,lx,lz,a=heading){return {x:x+lx*Math.cos(a)+lz*Math.sin(a),z:z-lx*Math.sin(a)+lz*Math.cos(a)};}
 function within(x,z,margin=.5){return Number.isFinite(x)&&Number.isFinite(z)&&Math.abs(x)<=worldLimit-margin&&Math.abs(z)<=worldLimit-margin;}
 function slopeAt(x,z){const e=.2;return Math.hypot((height(x+e,z)-height(x-e,z))/(2*e),(height(x,z+e)-height(x,z-e))/(2*e));}
 function support(x,z,a=heading){let y=-Infinity;for(const [lx,lz]of [[0,0],...contacts]){const p=point(x,z,lx,lz,a),h=height(p.x,p.z);if(!Number.isFinite(h)||!within(p.x,p.z)||slopeAt(p.x,p.z)>MOUNT_LIMITS.slope)return null;y=Math.max(y,h);}return y+.012;}
 // Wing boxes enclose both tiers'120Hz exported wing geometry plus .12m padding,
 // including sampled ground/flight SLERP blends (authoring wing-envelopes.json).
 // Torso, rider, head and appendages have separate vertical bands. Tree/rock
 // cylinders retain their measured heights; authored wall poles get a safe default.
 function transitionalEnvelope(){return kind==='gryphon'&&(['takeoff','landing'].includes(phase)||phase==='riding'&&landingSettled<.35);}
 function probes(id=kind,air=airborne(),transitional=transitionalEnvelope()){
  const p=[{x:0,z:-.65,r:.64,lo:.25,hi:2.10},{x:0,z:.05,r:.68,lo:.20,hi:2.1},{x:0,z:.73,r:.63,lo:.4,hi:2.3},{x:0,z:0,r:.52,lo:1.85,hi:3.35}];
  if(id==='stag')p.push({x:0,z:1.43,r:.66,lo:1.8,hi:3.8},{x:-.85,z:1.15,r:.76,lo:2.35,hi:3.86},{x:.85,z:1.15,r:.76,lo:2.35,hi:3.86},{x:0,z:-1.12,r:.35,lo:1,hi:2});
  else{p.push({x:0,z:1.53,r:.58,lo:1.25,hi:2.85},{x:0,z:-1.6,r:.58,lo:1.05,hi:2.15},{x:0,z:-2.23,r:.69,lo:.45,hi:1.98});for(const sign of [-1,1])p.push({x:sign*(air||transitional?1.75:1.03),z:.278,rx:air||transitional?1.70:.97,rz:.958,lo:transitional?.26:air?.48:1.30,hi:!air||transitional?4.35:3.20});}
  if(!air)p.push({x:0,z:0,r:1.02,lo:.05,hi:.65});return p;
 }
 // Transform the bounded collision envelope with the same terrain lean as the
 // visible rig. This keeps high antlers/wing tips inside their proxies on slopes.
 function terrainTilt(x,z,a){const e=.35,dx=(height(x+e,z)-height(x-e,z))/(e*2),dz=(height(x,z+e)-height(x,z-e))/(e*2);return {x:T.MathUtils.clamp(-Math.atan(dx*Math.sin(a)+dz*Math.cos(a)),-MOUNT_LIMITS.maxTilt,MOUNT_LIMITS.maxTilt),z:T.MathUtils.clamp(Math.atan(dx*Math.cos(a)-dz*Math.sin(a)),-MOUNT_LIMITS.maxTilt,MOUNT_LIMITS.maxTilt)};}
 function tiltedProbe(p,tilt){if(Math.abs(tilt.x)+Math.abs(tilt.z)<.001)return p;const cx=Math.cos(tilt.x),sx=Math.sin(tilt.x),cz=Math.cos(tilt.z),sz=Math.sin(tilt.z),y=(p.lo+p.hi)/2,hy=(p.hi-p.lo)/2,rx=p.rx??p.r,rz=p.rz??p.r,centerY=(p.x*sz+y*cz)*cx-p.z*sx,halfY=Math.abs(cx*sz)*rx+Math.abs(cx*cz)*hy+Math.abs(sx)*rz;return {x:p.x*cz-y*sz,z:(p.x*sz+y*cz)*sx+p.z*cx,rx:Math.abs(cz)*rx+Math.abs(sz)*hy,rz:Math.abs(sx*sz)*rx+Math.abs(sx*cz)*hy+Math.abs(cx)*rz,lo:centerY-halfY,hi:centerY+halfY};}
 function volumeClear(x,y,z,a=heading,{id=kind,air=airborne(),terrain=true,transitional=transitionalEnvelope()}={}){
  if(!Number.isFinite(y))return false;const cs=Math.cos(a),sn=Math.sin(a),tilt=air?null:terrainTilt(x,z,a);
  for(const raw of probes(id,air,transitional)){const p=tilt?tiltedProbe(raw,tilt):raw,q=point(x,z,p.x,p.z,a),ex=p.rx===undefined?p.r:Math.abs(cs)*p.rx+Math.abs(sn)*p.rz,ez=p.rx===undefined?p.r:Math.abs(sn)*p.rx+Math.abs(cs)*p.rz;if(!within(q.x,q.z,0)||Math.abs(q.x)+ex+.03>worldLimit||Math.abs(q.z)+ez+.03>worldLimit)return false;
   if(terrain){const terrainProbe=air?p:raw,terrainCenter=point(x,z,terrainProbe.x,terrainProbe.z,a),samples=terrainProbe.rx===undefined?[[0,0]]:[[0,0],[-terrainProbe.rx,-terrainProbe.rz],[-terrainProbe.rx,terrainProbe.rz],[terrainProbe.rx,-terrainProbe.rz],[terrainProbe.rx,terrainProbe.rz]];for(const [lx,lz]of samples){const sample=point(terrainCenter.x,terrainCenter.z,lx,lz,a);if(height(sample.x,sample.z)>y+terrainProbe.lo-.04)return false;}}
   for(const s of getSolids()){const low=s.minY??height(s.x,s.z),high=s.maxY??low+5;if(y+p.hi+(air?0:.32)<=low||y+p.lo-(air?0:.32)>=high+.08)continue;const dx=s.x-q.x,dz=s.z-q.z,distance=p.rx===undefined?Math.hypot(dx,dz)-p.r:Math.hypot(Math.max(0,Math.abs(dx*cs-dz*sn)-p.rx),Math.max(0,Math.abs(dx*sn+dz*cs)-p.rz));if(distance<s.r+.055)return false;}}
  return true;
 }
 function turnToward(wanted,dt,air){const delta=Math.atan2(Math.sin(wanted-heading),Math.cos(wanted-heading)),amount=T.MathUtils.clamp(delta,-dt*(air?MOUNT_LIMITS.flightTurnRate:MOUNT_LIMITS.groundTurnRate),dt*(air?MOUNT_LIMITS.flightTurnRate:MOUNT_LIMITS.groundTurnRate)),steps=Math.max(1,Math.ceil(Math.abs(amount)/MOUNT_LIMITS.turnStep)),step=amount/steps;for(let i=0;i<steps;i++){const next=heading+step;if(!volumeClear(player.x,player.y,player.z,next,{air})){notify('坐骑转身空间不足，请先移到开阔处');break;}heading=next;}}
 function footClear(x,z){if(!within(x,z,.55)||slopeAt(x,z)>MOUNT_LIMITS.slope)return false;const y=height(x,z);for(const [dx,dz]of [[.42,0],[-.42,0],[0,.42],[0,-.42]])if(Math.abs(height(x+dx,z+dz)-y)>.30)return false;return getSolids().every(s=>Math.hypot(x-s.x,z-s.z)>=s.r+.52||y+2.08<(s.minY??height(s.x,s.z))||y>(s.maxY??height(s.x,s.z)+5)+.05);}
 function riderPathClear(from,to){const n=Math.max(2,Math.ceil(Math.hypot(to.x-from.x,to.z-from.z)/.15));for(let i=0;i<=n;i++){const t=i/n,x=from.x+(to.x-from.x)*t,z=from.z+(to.z-from.z)*t,y=from.y+(to.y-from.y)*t;if(!within(x,z,.52)||height(x,z)>y+.08)return false;for(const s of getSolids()){const low=s.minY??height(s.x,s.z),high=s.maxY??low+5;if(Math.hypot(x-s.x,z-s.z)<s.r+.5&&y+2.05>low&&y<high+.08)return false;}}return true;}
 function groundAt(x,z,a=heading,id=kind){const y=support(x,z,a);return y!==null&&volumeClear(x,y,z,a,{id,air:false})?y:null;}
 function validReturn(x,z,a=heading){if(footClear(x,z))lastReturn={x,z,heading:Math.atan2(Math.sin(a),Math.cos(a))};}
 function setClip(name,dt,rate=1){const r=activeRig();if(!r)return;r.turn.beforeMixer();const action=r.actions.get(name);if(r.clip!==name){const oldName=r.clip,old=r.actions.get(oldName);let startPhase=0;if(name==='walk'||name==='run'){const duty=name==='run'?.45:.62,amp=name==='run'?.55:.23;startPhase=duty/2;if(oldName==='walk'||oldName==='run'){const oldDuty=oldName==='run'?.45:.62,oldAmp=oldName==='run'?.55:.23,p=old.time/old.getClip().duration,offset=p%1<oldDuty?0:.5,f=(p+offset)%1,reach=f<oldDuty?oldAmp-2*oldAmp*f/oldDuty:-oldAmp+2*oldAmp*(f-oldDuty)/(1-oldDuty),mapped=T.MathUtils.clamp((amp-reach)/(2*amp)*duty,.02*duty,.98*duty);startPhase=(mapped-offset+1)%1;}}action.reset().setEffectiveTimeScale(rate).setEffectiveWeight(1).play();action.time=startPhase*action.getClip().duration;if(old)old.crossFadeTo(action,.26,false);r.clip=name;}action.setEffectiveTimeScale(rate);r.mixer.update(dt);}
 function setAlpha(alpha){lifecycleOpacity=alpha;alpha*=cameraOpacity;for(const m of activeRig()?.materials??[]){const transparent=alpha<.999;if(m.transparent!==transparent){m.transparent=transparent;m.needsUpdate=true;}m.opacity=alpha;m.depthWrite=!transparent;}}
 function alignGround(){const r=activeRig(),p=r.root.position,e=.35;const dx=(height(p.x+e,p.z)-height(p.x-e,p.z))/(e*2),dz=(height(p.x,p.z+e)-height(p.x,p.z-e))/(e*2),forward=dx*Math.sin(heading)+dz*Math.cos(heading),side=dx*Math.cos(heading)-dz*Math.sin(heading);r.root.rotation.set(T.MathUtils.clamp(-Math.atan(forward),-MOUNT_LIMITS.maxTilt,MOUNT_LIMITS.maxTilt),heading,T.MathUtils.clamp(Math.atan(side),-MOUNT_LIMITS.maxTilt,MOUNT_LIMITS.maxTilt),'YXZ');r.root.position.y=height(p.x,p.z);r.root.updateWorldMatrix(true,true);let correction=-Infinity;for(const n of contactNames){r.sockets[n].getWorldPosition(v);correction=Math.max(correction,height(v.x,v.z)-v.y+.01);}r.root.position.y+=Math.max(-.05,correction);r.root.updateWorldMatrix(true,true);}
 function groundSoles(r,correct=true){r.root.updateMatrixWorld(true);const updated=new Set(),clearances={};let minimum=Infinity;for(const sample of r.soles){if(!updated.has(sample.mesh)){sample.mesh.skeleton.update();updated.add(sample.mesh);}sample.mesh.getVertexPosition(sample.index,v).applyMatrix4(sample.mesh.matrixWorld);const gap=v.y-height(v.x,v.z);minimum=Math.min(minimum,gap);clearances[sample.leg]=Math.min(clearances[sample.leg]??Infinity,gap);}const wantedCorrection=correct?Math.max(0,.012-minimum):0,correction=Math.min(.25,wantedCorrection);if(correction>0){r.root.position.y+=correction;minimum+=correction;for(const key of Object.keys(clearances))clearances[key]+=correction;r.root.updateMatrixWorld(true);}r.support={minimum,correction,saturated:wantedCorrection>.25,clearances,samples:r.soles.length};return r.support;}
 function solveArm(index,socket,amount){const shoulder=hero.limbs[index===0?1:3],elbow=hero.elbows[index],sign=index===0?-1:1;socket.getWorldPosition(v);hero.body.worldToLocal(v);const origin=shoulder.position,target=v.clone().sub(origin),distance=target.length(),upper=elbow.position.length(),hand=new T.Vector3(0,-.315,.025),lower=hand.length();if(distance<.001)return;const d=T.MathUtils.clamp(distance,.05,upper+lower-.002),dir=target.normalize(),plane=new T.Vector3(sign,.1,.2);plane.addScaledVector(dir,-plane.dot(dir)).normalize();const along=(upper*upper-lower*lower+d*d)/(2*d),lift=Math.sqrt(Math.max(0,upper*upper-along*along)),bend=dir.clone().multiplyScalar(along).addScaledVector(plane,lift);quat.setFromUnitVectors(elbow.position.clone().normalize(),bend.clone().normalize());shoulder.quaternion.slerp(quat,amount);const fore=dir.clone().multiplyScalar(d).sub(bend).applyQuaternion(quat.clone().invert()).normalize();quat.setFromUnitVectors(hand.clone().normalize(),fore);elbow.quaternion.slerp(quat,amount);}
 function pose(amount=1,{lift=0}={}){const r=activeRig();if(!r)return;r.root.updateWorldMatrix(true,true);r.sockets.rider_seat.getWorldPosition(seat);r.sockets.rider_seat.getWorldQuaternion(bodyQ);invYaw.setFromAxisAngle(new T.Vector3(0,1,0),-heading);bodyQ.premultiply(invYaw).multiply(leanQ);hero.body.quaternion.slerpQuaternions(rest.get(hero.body).quaternion,bodyQ,amount);v.copy(seat).sub(r.root.position).applyQuaternion(invYaw);v2.copy(hipCenter).applyQuaternion(bodyQ);v.sub(v2);hero.body.position.copy(rest.get(hero.body).position).lerp(v,amount);hero.body.position.y+=lift;
  for(const [o,angles]of [[hero.limbs[0],[-1.02,0,-.55]],[hero.limbs[2],[-1.02,0,.55]],[hero.knees[0],[1.42,0,0]],[hero.knees[1],[1.42,0,0]],[hero.limbs[1],[-.6,0,-.1]],[hero.limbs[3],[-.6,0,.1]],[hero.elbows[0],[-.75,0,0]],[hero.elbows[1],[-.75,0,0]],[hero.cape,[.35,0,0]]]){quat.setFromEuler(new T.Euler(...angles));if(o===hero.limbs[0]||o===hero.limbs[2])quat.premultiply(basis.copy(leanQ).invert());o.quaternion.slerpQuaternions(rest.get(o).quaternion,quat,amount);}
  for(const ankle of hero.ankles)ankle.quaternion.copy(rest.get(ankle).quaternion);hero.sword.visible=amount<.08&&originalSwordVisible;hero.body.updateWorldMatrix(true,true);if(amount>.99){solveArm(0,r.sockets.rein_grip_L,1);solveArm(1,r.sockets.rein_grip_R,1);hero.body.updateWorldMatrix(true,true);}}
 function select(id){if(!MOUNT_TYPES[id])return fail('未知坐骑','unknown');if(owns())return fail('先安全下骑，再更换坐骑','busy');if(id==='gryphon'&&getQuest()!==2)return fail('交还两枚余烬并完成守灯人委托后，解锁曙翼狮鹫','locked');selected=id;return {ok:true};}
 function summon(id=selected){if(disposed)return fail('坐骑资源已释放','disposed');if(!isActive())return fail('请先继续旅程','inactive');const choice=select(id);if(!choice.ok)return choice;if(!isFootGrounded())return fail('落地后才能召唤坐骑','air');if(getEnemies().some(e=>e.hp>0&&Math.hypot(e.g.position.x-player.x,e.g.position.z-player.z)<8))return fail('先离开敌人 8 米，再召唤坐骑','combat');
  heading=hero.root.rotation.y;let candidate=null;for(const sign of [-1,1])for(const ahead of [.3,-1.5,1.5]){const p=point(player.x,player.z,sign*(id==='stag'?1.75:2.8),ahead),y=groundAt(p.x,p.z,heading,id);if(y===null||!riderPathClear({x:player.x,y:player.y,z:player.z},{...p,y:y+.92}))continue;candidate={...p,y};break;}
  if(!candidate)return fail('周围没有足够平坦开阔的空间召唤坐骑','space');validReturn(player.x,player.z,heading);kind=id;transition={from:player.clone(),to:new T.Vector3(candidate.x,candidate.y,candidate.z)};const r=activeRig();r.root.position.copy(transition.to);r.root.rotation.set(0,heading,0);r.root.visible=true;setClip(MOUNT_TYPES[id].idle,0);alignGround();groundSoles(r,true);transition.to.copy(r.root.position);setAlpha(0);change('summoning');stats.summons++;return {ok:true};}
 function exitCandidate(){const r=activeRig();for(const [side,back]of [[-MOUNT_TYPES[kind].exit,-.12],[MOUNT_TYPES[kind].exit,-.12],[-MOUNT_TYPES[kind].exit,-1.1],[MOUNT_TYPES[kind].exit,-1.1],[0,kind==='gryphon'?-3.2:-2]]){const p=point(player.x,player.z,side,back),y=height(p.x,p.z);if(footClear(p.x,p.z)&&riderPathClear({x:player.x,y:player.y+.925,z:player.z},{...p,y}))return {...p,y};}return null;}
 function dismount(){if(!isActive())return fail('请先继续旅程','inactive');if(phase==='foot')return fail('当前未骑乘','foot');if(airborne())return fail('先降落；空中不能下骑','air');if(phase!=='riding')return fail('请等待坐骑动作结束','busy');if(activeRig().turn.active)return fail('先松开移动，待转身踏步结束后再下骑','turning');if(kind==='gryphon'&&landingSettled<.35)return fail('待双脚站稳、收翼后再下骑','settling');const candidate=exitCandidate();if(!candidate)return fail('两侧与后方都没有安全落脚点，请移到空地','space');transition={from:player.clone(),to:new T.Vector3(candidate.x,candidate.y,candidate.z)};change('dismounting');return {ok:true};}
 function takeoff(){if(!isActive())return fail('请先继续旅程','inactive');if(kind!=='gryphon')return fail('苔冠鹿不能飞行','ground-mount');if(phase!=='riding')return airborne()?{ok:true}:fail('请先坐稳','busy');if(activeRig().turn.active)return fail('待转身踏步结束、四蹄站稳后再起飞','turning');for(let lift=0;lift<=2.1;lift+=.15)if(!volumeClear(player.x,player.y+lift,player.z,heading,{air:true,transitional:true}))return fail('展开双翼需要更开阔的地面和上方空间','ceiling');change('takeoff');stats.takeoffs++;return {ok:true};}
 function land(){if(!isActive())return fail('请先继续旅程','inactive');if(phase==='riding')return dismount();if(!['flying','takeoff'].includes(phase))return fail('请等待当前动作完成','busy');const floor=groundAt(player.x,player.z);if(floor===null)return fail('下方陡峭或有障碍，请移到开阔平地再降落','landing');for(let y=player.y;y>=floor;y-=.15)if(!volumeClear(player.x,y,player.z,heading,{air:y-floor>.7,transitional:true}))return fail('降落路径有障碍，请换一处空地','landing');transition={floor};change('landing');return {ok:true};}
 function reset({returnToGround=false}={}){if(returnToGround&&owns()){player.set(lastReturn.x,height(lastReturn.x,lastReturn.z),lastReturn.z);hero.root.rotation.y=lastReturn.heading;}for(const r of Object.values(rigs)){r.root.visible=false;r.groundBlend=0;r.turn.reset();r.mixer.stopAllAction();r.clip=null;}for(const [o,value]of rest){o.position.copy(value.position);o.quaternion.copy(value.quaternion);}hero.sword.visible=originalSwordVisible;phase='foot';kind=null;lifecycleOpacity=cameraOpacity=1;age=speed=verticalSpeed=0;transition=null;onRestore();onChange('foot');}
 function moveGround(dt,dx,dz,wantedHeading,slow){
  const r=activeRig(),oldX=player.x,oldZ=player.z,oldY=player.y,input=Math.min(1,Math.hypot(dx,dz)),desiredHeading=input>.08?Math.atan2(dx,dz):wantedHeading,turnDelta=Math.atan2(Math.sin(desiredHeading-heading),Math.cos(desiredHeading-heading)),turningHard=Math.abs(turnDelta)>MOUNT_LIMITS.groundMovingTurnRate*dt+.0001;
  if(!r.turn.active&&['walk','run'].includes(r.clip)&&(input<=.08||(slow?'walk':'run')!==r.clip)){if(r.turn.start(heading))r.turn.finish();}
  if(turningHard&&!r.turn.active){const next=heading+Math.sign(turnDelta)*Math.min(Math.abs(turnDelta),MOUNT_LIMITS.groundTurnRate*dt);if(volumeClear(player.x,player.y,player.z,next,{air:false})){if(!r.turn.start(heading))notify('坡面不适合原地踏步，请先走到较平缓处再转身');}else notify('坐骑转身空间不足，请先移到开阔处');}
  const previousHeading=heading;if(!r.turn.active&&!turningHard||r.turn.canRotate)turnToward(desiredHeading,dt,false);const angularDelta=heading-previousHeading;
  if(r.turn.active&&!turningHard)r.turn.finish();
  const wantedGait=input>.08&&!turningHard&&!r.turn.active?(slow?'walk':'run'):MOUNT_TYPES[kind].idle;if(['walk','run'].includes(wantedGait)&&r.clip!==wantedGait)r.groundBlend=.26;if(r.turn.active||!['walk','run'].includes(wantedGait))r.groundBlend=0;const blending=r.groundBlend>0,targetSpeed=input>.08&&!turningHard&&!r.turn.active&&!blending?(slow?MOUNT_LIMITS.walkSpeed:MOUNT_LIMITS.groundSpeed):0;if(blending)speed=0;else speed=T.MathUtils.damp(speed,targetSpeed,targetSpeed?6:12,dt);const facingError=Math.abs(Math.atan2(Math.sin(desiredHeading-heading),Math.cos(desiredHeading-heading))),travel=input>.08&&!turningHard&&!r.turn.active&&!blending&&facingError<.02?speed*input*dt:0,steps=Math.max(1,Math.ceil(travel/.15));
  for(let i=0;i<steps;i++){const x=player.x+Math.sin(heading)*travel/steps,z=player.z+Math.cos(heading)*travel/steps,y=groundAt(x,z);stats.steps++;if(y===null){notify('路面太陡或坐骑前方有障碍');break;}player.set(x,y,z);}
  const actualSpeed=Math.hypot(player.x-oldX,player.z-oldZ)/Math.max(dt,.001);r.root.position.copy(player);const name=wantedGait,playback=name==='run'?actualSpeed/6.11:name==='walk'?actualSpeed/.618:1;setClip(name,dt,blending?0:playback);r.groundBlend=Math.max(0,r.groundBlend-dt);alignGround();if(r.turn.active)r.root.position.y=Math.max(r.root.position.y,oldY-dt*2);else groundSoles(r,true);player.y=r.root.position.y;hero.root.rotation.y=heading;
  if(r.turn.active)r.turn.update(dt,{heading,angularDelta,wantsTurn:turningHard&&Math.abs(angularDelta)>1e-6});else r.turn.pinLocomotion({clip:r.clip,normalizedTime:r.actions.get(r.clip).time/r.actions.get(r.clip).getClip().duration,clearances:r.support.clearances});groundSoles(r,false);
  landingSettled+=dt;if(footClear(player.x,player.z))validReturn(player.x,player.z);else{const exit=exitCandidate();if(exit)validReturn(exit.x,exit.z);}pose();
 }
 function moveAir(dt,dx,dz,wantedHeading,ascend,descend){const r=activeRig(),takeoff=phase==='takeoff';if(takeoff){dx=dz=0;ascend=true;descend=false;}const goal=(ascend?MOUNT_LIMITS.ascent:0)-(descend?MOUNT_LIMITS.descent:0);verticalSpeed=T.MathUtils.damp(verticalSpeed,goal,6,dt);const length=Math.hypot(dx*MOUNT_LIMITS.flightSpeed*dt,dz*MOUNT_LIMITS.flightSpeed*dt,verticalSpeed*dt),steps=Math.max(1,Math.ceil(length/.15));turnToward(wantedHeading,dt,true);
  for(let i=0;i<steps;i++){let x=player.x+dx*MOUNT_LIMITS.flightSpeed*dt/steps,z=player.z+dz*MOUNT_LIMITS.flightSpeed*dt/steps,y=player.y+verticalSpeed*dt/steps;const floor=height(x,z),min=floor+(takeoff?0:.8),max=floor+MOUNT_LIMITS.maxAltitude;
   if(y>max){y=Math.max(player.y-MOUNT_LIMITS.descent*dt/steps,max);if(verticalSpeed>0)verticalSpeed=0;}if(y<min){y=Math.min(player.y+MOUNT_LIMITS.ascent*dt/steps,min);if(verticalSpeed<0)verticalSpeed=0;}
   if(y>max+.001||y<min-.001||!volumeClear(x,y,z,heading,{air:true})){x=player.x;z=player.z;y=T.MathUtils.clamp(player.y+verticalSpeed*dt/steps,height(x,z)+(takeoff?0:.8),height(x,z)+MOUNT_LIMITS.maxAltitude);if(!volumeClear(x,y,z,heading,{air:true})){y=player.y;verticalSpeed=0;}notify('双翼或上方空间受阻，请调整高度和方向');}
   player.set(x,y,z);stats.steps++;
  }
  r.root.position.copy(player);r.root.rotation.set(0,heading,0);hero.root.rotation.y=heading;setClip(ascend||descend||takeoff||Math.hypot(dx,dz)<.08?'flap':'glide',dt);pose();if(takeoff&&player.y-height(player.x,player.z)>=2){change('flying');onNotice('已起飞 · 按住空格上升，Shift 下降，降落按钮安全着陆');}}
 function update(dt,{dx=0,dz=0,heading:wantedHeading=hero.root.rotation.y,ascend=false,descend=false,slow=false}={}){if(disposed||!owns()||!isActive())return;dt=Math.max(0,Math.min(.05,dt));age+=dt;clock+=dt;const r=activeRig();
  if(phase==='summoning'){setAlpha(smooth(age/.55));setClip(MOUNT_TYPES[kind].idle,dt);pose(0);if(age>=.55)change('boarding');}
  else if(phase==='boarding'){const t=Math.min(1,age/1.05),travel=smooth((t-.28)/.72);player.lerpVectors(transition.from,transition.to,travel);hero.root.rotation.y=heading;setClip(MOUNT_TYPES[kind].idle,dt);pose(smooth(t/.65),{lift:.22*Math.sin(Math.PI*t)});if(t===1){player.copy(r.root.position);change('riding');landingSettled=1;stats.rides++;}}
  else if(phase==='riding')moveGround(dt,dx,dz,wantedHeading,slow);
  else if(phase==='flying'||phase==='takeoff')moveAir(dt,dx,dz,wantedHeading,ascend,descend);
  else if(phase==='landing'){const remaining=player.y-transition.floor;verticalSpeed=-Math.min(MOUNT_LIMITS.descent,Math.max(.35,remaining*3));const y=Math.max(transition.floor,player.y+verticalSpeed*dt);if(!volumeClear(player.x,y,player.z,heading,{air:y-transition.floor>.7})){change('flying');notify('降落空间发生变化，请换一处空地');return;}player.y=y;r.root.position.copy(player);setClip(remaining<.8?MOUNT_TYPES[kind].idle:'flap',dt);pose();if(player.y<=transition.floor+.001){alignGround();groundSoles(r,true);player.y=r.root.position.y;landingSettled=0;change('riding');stats.landings++;validReturn(player.x,player.z);onNotice('已安全着陆 · 等待收翼后可下骑');}}
  else if(phase==='dismounting'){const t=Math.min(1,age/1.05);player.lerpVectors(transition.from,transition.to,smooth(t/.72));hero.root.rotation.y=heading;setClip(MOUNT_TYPES[kind].idle,dt);groundSoles(r,true);pose(1-smooth((t-.25)/.75),{lift:.20*Math.sin(Math.PI*t)});if(t===1){validReturn(player.x,player.z);change('departing');stats.dismounts++;}}
  else if(phase==='departing'){setAlpha(1-smooth(age/.45));setClip(MOUNT_TYPES[kind].idle,dt);pose(0);if(age>=.45)reset();}
 }
 function snapshot(){return {turning:activeRig()?.turn.active??false,phase,kind,selected,name:kind?MOUNT_TYPES[kind].name:null,owned:owns(),airborne:airborne(),unlocked:{stag:true,gryphon:getQuest()===2},altitude:airborne()?Math.max(0,player.y-height(player.x,player.z)):0,verticalSpeed,canDismount:phase==='riding'&&!activeRig()?.turn.active&&(kind!=='gryphon'||landingSettled>=.35),lastReason};}
 function cameraDepth(position,target){if(!owns())return Infinity;const direction=new T.Vector3().copy(target).sub(position).normalize(),r=activeRig(),cs=Math.cos(heading),sn=Math.sin(heading);let depth=Infinity;for(const raw of probes()){const p=tiltedProbe(raw,{x:r.root.rotation.x,z:r.root.rotation.z}),q=point(r.root.position.x,r.root.position.z,p.x,p.z),lo=p.lo-(airborne()?0:.35),hi=p.hi+(airborne()?0:.4),centerY=r.root.position.y+(lo+hi)/2,extent=p.rx===undefined?p.r*Math.hypot(direction.x,direction.z):Math.abs(direction.x*cs-direction.z*sn)*p.rx+Math.abs(direction.x*sn+direction.z*cs)*p.rz;depth=Math.min(depth,(q.x-position.x)*direction.x+(centerY-position.y)*direction.y+(q.z-position.z)*direction.z-extent-(hi-lo)/2*Math.abs(direction.y));}return depth;}
 function diagnostics(){const r=activeRig(),sockets={};if(r){r.root.updateWorldMatrix(true,true);for(const [name,node]of Object.entries(r.sockets))sockets[name]=node.getWorldPosition(new T.Vector3()).toArray();}return {...snapshot(),turnGait:r?.turn.diagnostics()??null,groundGaitBlend:r?.groundBlend??0,soleSupport:r?{...r.support,clearances:{...r.support.clearances}}:null,disposed,cameraOpacity,lifecycleOpacity,transitionAge:age,root:r?{position:r.root.position.toArray(),rotation:r.root.rotation.toArray()}:null,clipNormalizedTime:r?.clip?r.actions.get(r.clip).time/r.actions.get(r.clip).getClip().duration:0,stats:{...stats},safeReturn:{...lastReturn},files:loads.map(v=>({...v,clips:[...v.clips]})),selectedTiers:1,activeModels:Object.values(rigs).filter(r=>r.root.visible).length,clip:r?.clip??null,clipTime:r?.actions.get(r.clip)?.time??0,sockets,heading,landingSettled,bodyOffset:hero.body.position.toArray(),limits:{...MOUNT_LIMITS},groundProbes:kind?probes(kind,false).length:0,flightProbes:probes('gryphon',true).length,envelope:kind?probes().map(p=>({...p})):[]};}
 function dispose(){if(disposed)return;reset();disposed=true;const geometries=new Set(),materials=new Set(),textures=new Set(),skeletons=new Set();for(const r of Object.values(rigs)){r.mixer.stopAllAction();r.mixer.uncacheRoot(r.root);scene.remove(r.root);r.root.traverse(o=>{if(!o.isMesh)return;geometries.add(o.geometry);if(o.skeleton)skeletons.add(o.skeleton);for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const value of Object.values(m))if(value?.isTexture)textures.add(value);}});}for(const g of geometries)g.dispose();for(const m of materials)m.dispose();for(const t of textures){t.dispose();t.image?.close?.();}for(const s of skeletons)s.dispose();}
 return {cameraDepth,setCameraOpacity(alpha){cameraOpacity=Math.max(0,Math.min(1,alpha));if(owns())setAlpha(lifecycleOpacity);},select,summon,dismount,takeoff,land,reset,update,dispose,cancelInput(){speed=0;verticalSpeed=0;activeRig()?.turn.finish();},snapshot,diagnostics,get owns(){return owns();},get airborne(){return airborne();},get cameraHeight(){if(phase==='summoning'||phase==='departing'||phase==='foot')return 1.65;if(phase==='boarding'){const t=Math.min(1,age/1.05);return 1.65+.97*smooth(t/.65)+.22*Math.sin(Math.PI*t);}if(phase==='dismounting'){const t=Math.min(1,age/1.05);return 1.65+.97*(1-smooth((t-.25)/.75))+.20*Math.sin(Math.PI*t);}return 2.62;},savePosition(){return owns()?{...lastReturn}:null;},damageAllowed(enemyY,reach=2.8){return !airborne()||player.y<=enemyY+reach;}};
}
