import {mountBinding} from './mounts-r14.mjs';
import {hasTextInputFocus,keyLabel} from './rpg-controls-r13.mjs?v=20261008-r14';
// One extra menu entry; touch reuses the existing three action targets in ride mode.
export function createMountUi({getSnapshot,mounts,report,clearInput,focusGame,closeOtherPanels=()=>{},isBlocked=()=>false}){
 const make=(tag,cls,text='')=>{const e=document.createElement(tag);e.className=cls;e.textContent=text;return e;};
 const button=make('button','mount-menu-button','坐骑'),menu=make('section','mount-menu rpg-panel'),title=make('strong','', '林间旅伴'),close=make('button','mount-menu-close','关闭'),help=make('p','mount-help','苔冠鹿可直接召唤；完成守灯人委托并交还两枚余烬后解锁曙翼狮鹫。召唤需要平地，并离敌人 8 米。'),stag=make('button','mount-stag','召唤苔冠鹿'),gryphon=make('button','mount-gryphon','召唤曙翼狮鹫'),status=make('div','mount-status');
 button.type=close.type=stag.type=gryphon.type='button';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','mount-menu-r14');menu.id='mount-menu-r14';menu.setAttribute('aria-label','坐骑选择');menu.hidden=true;status.setAttribute('role','status');menu.append(title,close,help,stag,gryphon);document.querySelector('.rpg-toolbar')?.append(button);document.body.append(menu,status);
 let shown=false,lastText='',mountedBefore=false,footHint=document.querySelector('#hint')?.textContent??'',footWorldLabel=document.querySelector('#world')?.getAttribute('aria-label')??'';const gate=new Set();
 function hide({focus=true}={}){shown=false;menu.hidden=true;button.setAttribute('aria-expanded','false');clearInput();if(focus)focusGame();}
 function open(){const s=getSnapshot();if(!s.playing||s.paused||s.dead||isBlocked())return;clearInput();closeOtherPanels();shown=true;menu.hidden=false;button.setAttribute('aria-expanded','true');close.focus();update();}
 function primary(){const s=getSnapshot(),m=mounts.snapshot();if(!s.playing||s.paused||s.dead||isBlocked())return;if(!m.owned){shown?hide():open();return;}const result=m.airborne?mounts.land():mounts.dismount();report(result);focusGame();}
 function summon(id){clearInput();const result=mounts.summon(id);report(result);if(result.ok)hide();}
 button.onclick=primary;close.onclick=()=>hide();stag.onclick=()=>summon('stag');gryphon.onclick=()=>summon('gryphon');
 for(const surface of [menu,button])for(const type of ['pointerdown','pointerup','click','dblclick','wheel','contextmenu'])surface.addEventListener(type,e=>{e.stopPropagation();if(type==='pointerdown')clearInput();if(type==='contextmenu')e.preventDefault();});
 const keydown=e=>{if(e.defaultPrevented||e.isComposing||e.ctrlKey||e.metaKey||e.altKey||hasTextInputFocus(e.target)||isBlocked())return;
  if(shown&&e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)hide();return;}
  const code=mountBinding(getSnapshot());if(e.code!==code)return;e.preventDefault();e.stopImmediatePropagation();if(!e.repeat&&!gate.has(code)){gate.add(code);primary();}};
 window.addEventListener('keydown',keydown,true);window.addEventListener('keyup',e=>gate.delete(e.code),true);window.addEventListener('blur',()=>{gate.clear();hide({focus:false});});
 function update(){const s=getSnapshot(),m=mounts.snapshot(),code=mountBinding(s),active=s.playing&&!s.paused&&!s.dead;const text=m.owned?(m.airborne?'降落':'下骑'):'坐骑';button.textContent=text+(code?' '+keyLabel(code):'');button.setAttribute('aria-label',text+(code?'（'+keyLabel(code)+'）':''));if(code)button.setAttribute('aria-keyshortcuts',keyLabel(code));else button.removeAttribute('aria-keyshortcuts');button.disabled=!active||isBlocked();gryphon.disabled=!m.unlocked.gryphon;gryphon.textContent=m.unlocked.gryphon?'召唤曙翼狮鹫':'曙翼狮鹫 · 完成守灯人委托后解锁';stag.disabled=m.owned;help.textContent=m.unlocked.gryphon?'选择旅伴。空地召唤；飞行按住空格上升、Shift 下降，按降落键着陆。骑乘时需下骑后战斗和互动。':'苔冠鹿可直接召唤；交还两枚余烬并完成守灯人委托后解锁曙翼狮鹫。召唤需要平地，并离敌人 8 米。';
  if(!active&&shown)hide({focus:false});if(m.owned&&shown)hide({focus:false});
  const attack=document.querySelector('#attack'),jump=document.querySelector('#jump'),dodge=document.querySelector('#dodge'),attackKey=keyLabel(s.baseBindings.attack);
  const hint=document.querySelector('#hint'),world=document.querySelector('#world');if(hint?.textContent.includes('Shift 闪避'))footHint=hint.textContent;if(world?.getAttribute('aria-label')?.includes('空格跳跃'))footWorldLabel=world.getAttribute('aria-label');
  if(m.owned){const controls=m.airborne?'按住空格上升 · 按住 Shift 下降':m.kind==='gryphon'?'空格起飞 · Shift 缓步':'Shift 缓步',action=m.airborne?'降落':'下骑';if(hint)hint.textContent=`WASD 骑行　左拖观察 / 右拖转向　双键前进 / 滚轮缩放　${controls}　${attackKey} ${action}　${keyLabel(s.inventoryCode)} 背包（不暂停）　需下骑后战斗 / 互动　Esc 关闭 / 暂停`;world?.setAttribute('aria-label',`${m.name}骑乘场景：WASD或摇杆移动，左拖观察、右拖转向，双键前进，滚轮缩放，${controls}，${attackKey}${action}，${keyLabel(s.inventoryCode)}背包不暂停；技能和互动需先下骑，飞行先降落。Esc关闭界面或暂停`);const stage={summoning:'召唤中',boarding:'上鞍中',riding:m.turning?'踏步转身':'地面骑乘',takeoff:'起飞中',flying:'飞行',landing:'降落中',dismounting:'下骑中',departing:'旅伴离开'}[m.phase];const detail=m.airborne?`离地 ${m.altitude.toFixed(1)} / 18 米 · 空格上升 · Shift下降 · ${attackKey}降落`:m.kind==='gryphon'?`空格起飞 · ${attackKey}下骑`:`WASD骑行 · Shift慢行 · ${attackKey}下骑`;const next=`${m.name} · ${stage} · ${detail}`;if(lastText!==next){status.textContent=next;lastText=next;}status.hidden=false;attack.textContent=m.airborne?'降落':'下骑';attack.setAttribute('aria-label',attack.textContent+'（'+attackKey+'）');jump.hidden=m.kind!=='gryphon';jump.textContent=m.airborne?'上升':'起飞';jump.setAttribute('aria-label',m.airborne?'按住上升（空格）':'起飞（空格）');dodge.hidden=m.kind!=='gryphon';dodge.textContent='下降';dodge.disabled=!m.airborne;dodge.setAttribute('aria-label','按住下降（Shift）');document.body.classList.add('is-mounted');
  }else{status.hidden=true;lastText='';if(mountedBefore){if(hint)hint.textContent=footHint;if(world)world.setAttribute('aria-label',footWorldLabel);attack.textContent='挥剑';attack.setAttribute('aria-label','挥剑（'+attackKey+'）');jump.hidden=dodge.hidden=false;jump.textContent='跳跃';jump.setAttribute('aria-label','跳跃（空格）');dodge.textContent='闪避';dodge.setAttribute('aria-label','闪避（Shift）');dodge.disabled=false;document.body.classList.remove('is-mounted');}}mountedBefore=m.owned;
 }
 return {open,hide,update,primary,isOpen:()=>shown};
}
