// Original, bounded RPG progression. Timers count active simulation time, never wall time.
export const SAVE_VERSION=2, SAVE_KEY='emberwild.rpg.save';
export const LIMITS=Object.freeze({opened:1024,killed:2048,explored:4096,saveBytes:400000,world:4096});
export const MAP_CELL_SIZE=8;
export const SKILLS=Object.freeze([
 Object.freeze({id:'emberStrike',name:'烬刃',description:'下一次挥剑造成 +2 伤害。重盾仍需绕后或等收招。',icon:'✦',cooldown:6,unlockLevel:1,kind:'skill'}),
 Object.freeze({id:'ward',name:'灯火护身',description:'4 秒内受到的伤害减少 65%。',icon:'◈',cooldown:14,duration:4,unlockLevel:1,kind:'skill'}),
 Object.freeze({id:'potion',name:'暖露药剂',description:'消耗 1 瓶恢复生命；满血不会消耗。',icon:'✚',cooldown:8,unlockLevel:1,kind:'item'})
]);
const SKILL_IDS=new Set(SKILLS.map(s=>s.id));
const PROTECTED=new Set(['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight','Space','Escape','Tab','Enter','ControlLeft','ControlRight','AltLeft','AltRight','MetaLeft','MetaRight',...Array.from({length:10},(_,i)=>'Digit'+i),...Array.from({length:10},(_,i)=>'Numpad'+i)]);
const aliasPattern=/^(Key[A-Z]|Backquote|Minus|Equal|BracketLeft|BracketRight|Backslash|Semicolon|Quote|Comma|Period|Slash)$/;
const isObject=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
const bounded=(v,min,max,fallback=0)=>typeof v==='number'&&Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback;
const integer=(v,min,max,fallback=0)=>Math.floor(bounded(v,min,max,fallback));
export const levelForXp=xp=>Math.min(10,1+Math.floor((Math.sqrt(1+8*Math.max(0,xp)/45)-1)/2));
export const xpForLevel=level=>45*(level-1)*level/2;
export const maxHp=s=>100+(levelForXp(s.xp)-1)*10;
export const weaponDamage=s=>1+s.weaponLevel*.5;
export const potionHealing=s=>45+s.supplyLevel*15;
export function createRpgState(){return {hp:100,gold:0,quest:0,relics:new Set(),opened:new Set(),killed:new Set(),dead:false,xp:0,inventory:{potions:3,scrap:0},weaponLevel:0,supplyLevel:0,cooldowns:{emberStrike:0,ward:0,potion:0},wardRemaining:0,motion:{dodgeCd:0,attackRecovery:0},hotbar:['emberStrike','ward','potion',null,null,null,null,null,null],aliases:['KeyQ','KeyR',null,null,null,null,null,null,null],baseBindings:{attack:'KeyF',interact:'KeyE'},preferences:{showMinimap:true,showHints:true,music:true,musicVolume:.35},explored:new Set(),mapRevision:0,position:{x:0,z:10,heading:Math.PI},activeSeconds:0};}
export function grantXp(s,amount){const previous=levelForXp(s.xp);s.xp=integer(s.xp+amount,0,1000000);const levels=levelForXp(s.xp)-previous;if(levels>0)s.hp=Math.min(maxHp(s),s.hp+levels*10);return levels;}
function reward(s,{gold=0,xp=0,scrap=0,potions=0}={}){s.gold=integer(s.gold+gold,0,999999);s.inventory.scrap=integer(s.inventory.scrap+scrap,0,9999);s.inventory.potions=integer(s.inventory.potions+potions,0,99);grantXp(s,xp);}
const chestId=id=>typeof id==='string'&&(id==='old-watch'||id==='moon-cache'||/^wild:-?\d{1,3},-?\d{1,3}$/.test(id));
const enemyId=id=>typeof id==='string'&&/^enemy:-?\d{1,4}(?:\.\d{1,3})?,-?\d{1,4}(?:\.\d{1,3})?:[01]$/.test(id);
const cellId=id=>typeof id==='string'&&/^-?\d{1,3},-?\d{1,3}$/.test(id)&&id.split(',').every(n=>Math.abs(Number(n))<=LIMITS.world/MAP_CELL_SIZE);
export function claimChest(s,id){if(s.dead||!chestId(id)||s.opened.has(id)||s.opened.size>=LIMITS.opened)return false;s.opened.add(id);reward(s,{gold:25,xp:12,scrap:2,potions:1});s.hp=Math.min(maxHp(s),s.hp+30);return true;}
export function claimKill(s,id,type=0){if(!enemyId(id)||s.killed.has(id)||s.killed.size>=LIMITS.killed)return false;s.killed.add(id);reward(s,{gold:type?15:8,xp:type?30:15,scrap:type?2:1});return true;}
export function claimRelic(s,id){if(s.dead||s.quest!==1||!['tower','pool'].includes(id)||s.relics.has(id))return false;s.relics.add(id);reward(s,{xp:25});return true;}
export function talkToWarden(s){if(s.dead)return '先回营地休整吧。';if(!s.quest){s.quest=1;return '古塔与月池的灯芯熄灭了。沿金色路标带回两枚余烬吧。重盾守卫收招时再进攻；烬刃、护身与药剂都能帮上忙。宝箱与守卫会掉落锻片，回来可以修整装备。';}if(s.quest===1&&s.relics.has('tower')&&s.relics.has('pool')){s.quest=2;reward(s,{gold:100,xp:70,scrap:3});s.hp=maxHp(s);return '灯火重燃了。收下 100 星币、3 枚锻片与 70 经验。你的生命已恢复。在背包的营地工坊里强化旅剑、改良药剂，再去探索林地深处。';}return s.quest===2?'灯火始终为你留着。营地工坊可强化旅剑、改良药剂，也能补充药剂。':'古塔与月池各有一枚余烬。先避开重盾蓄力，再在收招时反击。回到营地可使用工坊。';}
export function takeDamage(s,amount,invulnerable=false){if(s.dead||invulnerable||!Number.isFinite(amount)||amount<=0)return false;const damage=Math.max(1,Math.ceil(amount*(s.wardRemaining>0?.35:1)));s.hp=Math.max(0,s.hp-damage);s.dead=s.hp<=0;return true;}
export function retryAtCamp(s){s.hp=maxHp(s);s.dead=false;s.wardRemaining=0;s.position={x:0,z:10,heading:Math.PI};}
export function tickRpg(s,dt,{paused=false,dead=s.dead}={}){if(paused||dead||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.25);for(const id of SKILL_IDS)s.cooldowns[id]=Math.max(0,s.cooldowns[id]-dt);s.wardRemaining=Math.max(0,s.wardRemaining-dt);s.activeSeconds=Math.min(100000000,s.activeSeconds+dt);}
export function activateSkill(s,id,{active=true,canAttack=true}={}){if(!active||s.dead)return {ok:false,reason:'旅程暂停时无法使用'};if(!SKILL_IDS.has(id))return {ok:false,reason:'空技能栏'};if(s.cooldowns[id]>0)return {ok:false,reason:'技能还在冷却'};if(id==='emberStrike'&&!canAttack)return {ok:false,reason:'先完成当前动作'};if(id==='potion'){if(!s.inventory.potions)return {ok:false,reason:'药剂用完了，可在营地补充'};if(s.hp>=maxHp(s))return {ok:false,reason:'生命已满'};s.inventory.potions--;s.hp=Math.min(maxHp(s),s.hp+potionHealing(s));}if(id==='ward')s.wardRemaining=4;s.cooldowns[id]=SKILLS.find(a=>a.id===id).cooldown;return {ok:true,id};}
export function setHotbarSlot(s,index,id){if(!Number.isInteger(index)||index<0||index>8||id!==null&&!SKILL_IDS.has(id))return {ok:false,reason:'无效技能或栏位'};s.hotbar[index]=id;return {ok:true};}
export function swapHotbarSlots(s,from,to){if(![from,to].every(i=>Number.isInteger(i)&&i>=0&&i<9))return {ok:false,reason:'无效栏位'};[s.hotbar[from],s.hotbar[to]]=[s.hotbar[to],s.hotbar[from]];return {ok:true};}
export function validAlias(code){return typeof code==='string'&&aliasPattern.test(code)&&!PROTECTED.has(code);}
export function setHotbarAlias(s,index,code,{swapBase=false}={}){if(!Number.isInteger(index)||index<0||index>8)return {ok:false,reason:'无效栏位'};if(code!==null&&!validAlias(code))return {ok:false,reason:'移动、跳跃、闪避与数字键需要保留'};if(code!==null&&s.aliases.some((a,i)=>i!==index&&a===code))return {ok:false,reason:'这个按键已绑定其他栏位'};const action=Object.keys(s.baseBindings).find(a=>s.baseBindings[a]===code);if(action){const replacement=s.aliases[index];if(!replacement||!validAlias(replacement)||Object.values(s.baseBindings).includes(replacement))return {ok:false,reason:'先为这个栏位设置一个空闲辅助键，再与基础操作交换'};if(!swapBase)return {ok:false,reason:'需要确认交换基础操作按键',baseConflict:{action,from:code,to:replacement}};s.baseBindings[action]=replacement;}s.aliases[index]=code;return {ok:true};}
export function setRpgPreference(s,key,value){if(['showMinimap','showHints','music'].includes(key)&&typeof value==='boolean')s.preferences[key]=value;else if(key==='musicVolume'&&typeof value==='number'&&Number.isFinite(value))s.preferences[key]=bounded(value,0,1);else return {ok:false,reason:'无效设置'};return {ok:true};}
export function campOffers(s){const weaponCost=[{gold:40,scrap:4},{gold:90,scrap:8}][s.weaponLevel]??{gold:0,scrap:0};const offers={weapon:{cost:weaponCost,maxed:s.weaponLevel>=2},supplies:{cost:{gold:30,scrap:3},maxed:s.supplyLevel>=1},potion:{cost:{gold:10,scrap:0},maxed:s.inventory.potions>=99}};for(const o of Object.values(offers))o.available=!o.maxed&&s.gold>=o.cost.gold&&s.inventory.scrap>=o.cost.scrap;return offers;}
export function purchaseAtCamp(s,kind,{nearby=false}={}){if(s.dead)return {ok:false,reason:'先在营地重试'};if(!nearby)return {ok:false,reason:'请回到灯火营地使用工坊'};const offer=campOffers(s)[kind];if(!offer)return {ok:false,reason:'无效工坊项目'};if(offer.maxed)return {ok:false,reason:'已达到上限'};if(!offer.available)return {ok:false,reason:'星币或锻片不足'};s.gold-=offer.cost.gold;s.inventory.scrap-=offer.cost.scrap;if(kind==='weapon')s.weaponLevel++;if(kind==='supplies'){s.supplyLevel++;s.inventory.potions=Math.min(99,s.inventory.potions+2);}if(kind==='potion')s.inventory.potions++;return {ok:true,kind};}
export function discoverAround(s,x,z){if(!Number.isFinite(x)||!Number.isFinite(z))return false;const cx=Math.floor(x/MAP_CELL_SIZE),cz=Math.floor(z/MAP_CELL_SIZE);let changed=false;for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++){const key=`${cx+dx},${cz+dz}`;if(s.explored.size<LIMITS.explored&&cellId(key)&&!s.explored.has(key)){s.explored.add(key);changed=true;}}if(changed)s.mapRevision++;return changed;}
function readSet(value,limit,valid){return new Set((Array.isArray(value)?value.slice(0,limit):[]).filter(valid));}
export function validateState(raw){const s=createRpgState();if(!isObject(raw))return s;s.xp=integer(raw.xp,0,1000000);s.gold=integer(raw.gold,0,999999);s.quest=integer(raw.quest,0,2);s.relics=readSet(raw.relics,2,id=>['tower','pool'].includes(id));if(s.quest===0)s.relics.clear();if(s.quest===2&&s.relics.size!==2)s.quest=1;s.opened=readSet(raw.opened,LIMITS.opened,chestId);s.killed=readSet(raw.killed,LIMITS.killed,enemyId);s.explored=readSet(raw.explored,LIMITS.explored,cellId);s.mapRevision=s.explored.size;s.hp=bounded(raw.hp,0,maxHp(s),maxHp(s));s.dead=raw.dead===true||s.hp===0;if(s.dead)s.hp=0;s.weaponLevel=integer(raw.weaponLevel,0,2);s.supplyLevel=integer(raw.supplyLevel,0,1);if(isObject(raw.inventory)){s.inventory.potions=integer(raw.inventory.potions,0,99,3);s.inventory.scrap=integer(raw.inventory.scrap,0,9999);}for(const id of SKILL_IDS)s.cooldowns[id]=bounded(raw.cooldowns?.[id],0,SKILLS.find(a=>a.id===id).cooldown);s.wardRemaining=bounded(raw.wardRemaining,0,4);s.motion={dodgeCd:bounded(raw.motion?.dodgeCd,0,1.05),attackRecovery:bounded(raw.motion?.attackRecovery,0,.44)};if(Array.isArray(raw.hotbar))s.hotbar=Array.from({length:9},(_,i)=>SKILL_IDS.has(raw.hotbar[i])?raw.hotbar[i]:null);if(isObject(raw.baseBindings)){const a=raw.baseBindings.attack,i=raw.baseBindings.interact;if(validAlias(a)&&validAlias(i)&&a!==i)s.baseBindings={attack:a,interact:i};}if(Array.isArray(raw.aliases)){const used=new Set(Object.values(s.baseBindings));s.aliases=Array.from({length:9},(_,i)=>{const a=raw.aliases[i];if(!validAlias(a)||used.has(a))return null;used.add(a);return a;});}s.aliases=s.aliases.map(a=>Object.values(s.baseBindings).includes(a)?null:a);if(isObject(raw.preferences))for(const key of Object.keys(s.preferences))if(Object.hasOwn(raw.preferences,key))setRpgPreference(s,key,raw.preferences[key]);if(isObject(raw.position))s.position={x:bounded(raw.position.x,-LIMITS.world,LIMITS.world,0),z:bounded(raw.position.z,-LIMITS.world,LIMITS.world,10),heading:bounded(raw.position.heading,-Math.PI*2,Math.PI*2,Math.PI)};s.activeSeconds=bounded(raw.activeSeconds,0,100000000);return s;}
export function encodeSave(s){return JSON.stringify({version:SAVE_VERSION,state:{...s,relics:[...s.relics],opened:[...s.opened],killed:[...s.killed],explored:[...s.explored]}});}
// Compatibility reader for the defined v1 prototype schema; no published v1 save is assumed.
export function decodeSave(text){if(typeof text!=='string'||text.length>LIMITS.saveBytes)return {state:createRpgState(),status:'corrupt',writable:false};let data;try{data=JSON.parse(text);}catch{return {state:createRpgState(),status:'corrupt',writable:false};}if(!isObject(data)||!Number.isInteger(data.version))return {state:createRpgState(),status:'corrupt',writable:false};if(data.version>SAVE_VERSION)return {state:createRpgState(),status:'future',writable:false};if(data.version<1||!isObject(data.state))return {state:createRpgState(),status:'corrupt',writable:false};const raw={...data.state};if(data.version===1){raw.inventory??={potions:raw.potions??3,scrap:raw.materials??0};raw.xp??=0;}return {state:validateState(raw),status:data.version===SAVE_VERSION?'loaded':'migrated',writable:true};}
export function loadRpgSave(storage){try{if(!storage)return {state:createRpgState(),status:'unavailable',writable:false};const text=storage.getItem(SAVE_KEY);return text===null?{state:createRpgState(),status:'new',writable:true}:decodeSave(text);}catch{return {state:createRpgState(),status:'unavailable',writable:false};}}
export function writeRpgSave(storage,s,{writable=true}={}){if(!writable)return {ok:false,status:'protected'};try{if(!storage)return {ok:false,status:'unavailable'};const text=encodeSave(s);if(text.length>LIMITS.saveBytes)return {ok:false,status:'full'};storage.setItem(SAVE_KEY,text);return {ok:true,status:'saved'};}catch{return {ok:false,status:'unavailable'};}}
