'use strict';

/* ============================================================
   题库数据 · 飞鸟背单词 FLAPPY WORDS
   词汇格式：{ en: 'apple', zh: '苹果' }
   语法格式：{ prompt: 'I ___ a student.', options: [...], answer: 'am' }
   说明：
   - 拼单词模式只使用 3~9 个字母的词汇；
   - 闯关选择模式 = 语法题 + 词汇选择题（看中文选英文，干扰项同难度随机抽取）；
   - 可自由增删，游戏内 ?selftest 会校验格式。
   ============================================================ */

const VOCAB = {
  easy: [
    { en: 'apple', zh: '苹果' },
    { en: 'banana', zh: '香蕉' },
    { en: 'orange', zh: '橙子' },
    { en: 'grape', zh: '葡萄' },
    { en: 'pear', zh: '梨' },
    { en: 'lemon', zh: '柠檬' },
    { en: 'mango', zh: '芒果' },
    { en: 'dog', zh: '狗' },
    { en: 'cat', zh: '猫' },
    { en: 'bird', zh: '鸟' },
    { en: 'fish', zh: '鱼' },
    { en: 'duck', zh: '鸭子' },
    { en: 'rabbit', zh: '兔子' },
    { en: 'tiger', zh: '老虎' },
    { en: 'lion', zh: '狮子' },
    { en: 'panda', zh: '熊猫' },
    { en: 'monkey', zh: '猴子' },
    { en: 'book', zh: '书' },
    { en: 'pen', zh: '钢笔' },
    { en: 'desk', zh: '书桌' },
    { en: 'chair', zh: '椅子' },
    { en: 'pencil', zh: '铅笔' },
    { en: 'ruler', zh: '尺子' },
    { en: 'bag', zh: '书包' },
    { en: 'red', zh: '红色的' },
    { en: 'blue', zh: '蓝色的' },
    { en: 'green', zh: '绿色的' },
    { en: 'yellow', zh: '黄色的' },
    { en: 'black', zh: '黑色的' },
    { en: 'white', zh: '白色的' },
    { en: 'big', zh: '大的' },
    { en: 'small', zh: '小的' },
    { en: 'tall', zh: '高的' },
    { en: 'short', zh: '矮的' },
    { en: 'long', zh: '长的' },
    { en: 'run', zh: '跑' },
    { en: 'jump', zh: '跳' },
    { en: 'swim', zh: '游泳' },
    { en: 'walk', zh: '走路' },
    { en: 'sing', zh: '唱歌' },
    { en: 'dance', zh: '跳舞' },
    { en: 'mother', zh: '妈妈' },
    { en: 'father', zh: '爸爸' },
    { en: 'sister', zh: '姐妹' },
    { en: 'family', zh: '家庭' },
    { en: 'friend', zh: '朋友' },
    { en: 'school', zh: '学校' },
    { en: 'teacher', zh: '老师' },
    { en: 'student', zh: '学生' },
    { en: 'water', zh: '水' },
    { en: 'bread', zh: '面包' },
    { en: 'milk', zh: '牛奶' },
    { en: 'egg', zh: '鸡蛋' },
    { en: 'rice', zh: '米饭' },
    { en: 'happy', zh: '高兴的' },
    { en: 'sad', zh: '伤心的' },
    { en: 'angry', zh: '生气的' },
    { en: 'tired', zh: '疲倦的' },
    { en: 'morning', zh: '早晨' },
    { en: 'night', zh: '夜晚' },
    { en: 'hand', zh: '手' },
    { en: 'head', zh: '头' },
    { en: 'eye', zh: '眼睛' },
    { en: 'ear', zh: '耳朵' },
    { en: 'mouth', zh: '嘴巴' },
    { en: 'nose', zh: '鼻子' },
    { en: 'door', zh: '门' },
    { en: 'window', zh: '窗户' },
    { en: 'sun', zh: '太阳' },
    { en: 'moon', zh: '月亮' },
    { en: 'star', zh: '星星' },
    { en: 'tree', zh: '树' },
    { en: 'flower', zh: '花' },
    { en: 'rain', zh: '雨' },
    { en: 'snow', zh: '雪' },
    { en: 'wind', zh: '风' },
    { en: 'hot', zh: '热的' },
    { en: 'cold', zh: '冷的' },
    { en: 'warm', zh: '温暖的' },
    { en: 'cool', zh: '凉爽的' },
    { en: 'fast', zh: '快的' },
    { en: 'slow', zh: '慢的' },
    { en: 'eat', zh: '吃' },
    { en: 'drink', zh: '喝' },
    { en: 'read', zh: '阅读' },
    { en: 'write', zh: '写' },
    { en: 'play', zh: '玩' },
    { en: 'sleep', zh: '睡觉' },
    { en: 'open', zh: '打开' },
    { en: 'close', zh: '关闭' },
    { en: 'one', zh: '一' },
    { en: 'two', zh: '二' },
    { en: 'three', zh: '三' },
    { en: 'four', zh: '四' },
    { en: 'five', zh: '五' },
    { en: 'six', zh: '六' },
    { en: 'seven', zh: '七' },
    { en: 'eight', zh: '八' },
    { en: 'nine', zh: '九' },
    { en: 'ten', zh: '十' }
  ],
  medium: [
    { en: 'beautiful', zh: '美丽的' },
    { en: 'important', zh: '重要的' },
    { en: 'different', zh: '不同的' },
    { en: 'difficult', zh: '困难的' },
    { en: 'interesting', zh: '有趣的' },
    { en: 'wonderful', zh: '精彩的' },
    { en: 'expensive', zh: '昂贵的' },
    { en: 'delicious', zh: '美味的' },
    { en: 'healthy', zh: '健康的' },
    { en: 'hospital', zh: '医院' },
    { en: 'library', zh: '图书馆' },
    { en: 'museum', zh: '博物馆' },
    { en: 'restaurant', zh: '餐馆' },
    { en: 'supermarket', zh: '超市' },
    { en: 'airport', zh: '机场' },
    { en: 'station', zh: '车站' },
    { en: 'mountain', zh: '山' },
    { en: 'river', zh: '河流' },
    { en: 'forest', zh: '森林' },
    { en: 'island', zh: '岛屿' },
    { en: 'weather', zh: '天气' },
    { en: 'season', zh: '季节' },
    { en: 'spring', zh: '春天' },
    { en: 'summer', zh: '夏天' },
    { en: 'autumn', zh: '秋天' },
    { en: 'winter', zh: '冬天' },
    { en: 'holiday', zh: '假期' },
    { en: 'travel', zh: '旅行' },
    { en: 'exercise', zh: '锻炼' },
    { en: 'practice', zh: '练习' },
    { en: 'knowledge', zh: '知识' },
    { en: 'experience', zh: '经验' },
    { en: 'future', zh: '未来' },
    { en: 'history', zh: '历史' },
    { en: 'science', zh: '科学' },
    { en: 'subject', zh: '科目' },
    { en: 'question', zh: '问题' },
    { en: 'answer', zh: '答案' },
    { en: 'mistake', zh: '错误' },
    { en: 'succeed', zh: '成功' },
    { en: 'achieve', zh: '实现' },
    { en: 'believe', zh: '相信' },
    { en: 'remember', zh: '记得' },
    { en: 'forget', zh: '忘记' },
    { en: 'understand', zh: '理解' },
    { en: 'explain', zh: '解释' },
    { en: 'decide', zh: '决定' },
    { en: 'choose', zh: '选择' },
    { en: 'change', zh: '改变' },
    { en: 'improve', zh: '提高' },
    { en: 'protect', zh: '保护' },
    { en: 'pollution', zh: '污染' },
    { en: 'energy', zh: '能量' },
    { en: 'culture', zh: '文化' },
    { en: 'language', zh: '语言' },
    { en: 'foreign', zh: '外国的' },
    { en: 'country', zh: '国家' },
    { en: 'village', zh: '村庄' },
    { en: 'bridge', zh: '桥' },
    { en: 'garden', zh: '花园' },
    { en: 'market', zh: '市场' },
    { en: 'medicine', zh: '药' },
    { en: 'message', zh: '信息' },
    { en: 'picture', zh: '图画' },
    { en: 'problem', zh: '难题' },
    { en: 'reason', zh: '原因' },
    { en: 'result', zh: '结果' },
    { en: 'example', zh: '例子' },
    { en: 'moment', zh: '片刻' },
    { en: 'noise', zh: '噪音' },
    { en: 'voice', zh: '嗓音' },
    { en: 'smile', zh: '微笑' },
    { en: 'laugh', zh: '大笑' },
    { en: 'cry', zh: '哭' },
    { en: 'dream', zh: '梦想' },
    { en: 'hope', zh: '希望' },
    { en: 'wish', zh: '祝愿' },
    { en: 'brave', zh: '勇敢的' },
    { en: 'clever', zh: '聪明的' },
    { en: 'kind', zh: '善良的' },
    { en: 'lazy', zh: '懒惰的' },
    { en: 'lucky', zh: '幸运的' },
    { en: 'quiet', zh: '安静的' }
  ],
  hard: [
    { en: 'ambitious', zh: '有雄心的' },
    { en: 'significant', zh: '重要的' },
    { en: 'efficient', zh: '高效的' },
    { en: 'sufficient', zh: '充足的' },
    { en: 'abundant', zh: '丰富的' },
    { en: 'accurate', zh: '准确的' },
    { en: 'appropriate', zh: '恰当的' },
    { en: 'beneficial', zh: '有益的' },
    { en: 'controversial', zh: '有争议的' },
    { en: 'convincing', zh: '令人信服的' },
    { en: 'crucial', zh: '至关重要的' },
    { en: 'deliberate', zh: '故意的' },
    { en: 'dramatic', zh: '戏剧性的' },
    { en: 'enthusiastic', zh: '热情的' },
    { en: 'inevitable', zh: '不可避免的' },
    { en: 'magnificent', zh: '壮丽的' },
    { en: 'mysterious', zh: '神秘的' },
    { en: 'numerous', zh: '众多的' },
    { en: 'optimistic', zh: '乐观的' },
    { en: 'pessimistic', zh: '悲观的' },
    { en: 'professional', zh: '专业的' },
    { en: 'remarkable', zh: '非凡的' },
    { en: 'sophisticated', zh: '复杂精密的' },
    { en: 'spectacular', zh: '壮观的' },
    { en: 'tremendous', zh: '巨大的' },
    { en: 'urgent', zh: '紧急的' },
    { en: 'vulnerable', zh: '脆弱的' },
    { en: 'comprehensive', zh: '全面的' },
    { en: 'extraordinary', zh: '非凡的' },
    { en: 'fascinating', zh: '迷人的' },
    { en: 'phenomenon', zh: '现象' },
    { en: 'philosophy', zh: '哲学' },
    { en: 'psychology', zh: '心理学' },
    { en: 'economy', zh: '经济' },
    { en: 'politics', zh: '政治' },
    { en: 'society', zh: '社会' },
    { en: 'technology', zh: '技术' },
    { en: 'innovation', zh: '创新' },
    { en: 'artificial', zh: '人造的' },
    { en: 'intelligent', zh: '智能的' },
    { en: 'civilization', zh: '文明' },
    { en: 'evolution', zh: '进化' },
    { en: 'revolution', zh: '革命' },
    { en: 'agriculture', zh: '农业' },
    { en: 'commerce', zh: '商业' },
    { en: 'consequence', zh: '后果' },
    { en: 'circumstance', zh: '环境；情况' },
    { en: 'opportunity', zh: '机会' },
    { en: 'challenge', zh: '挑战' },
    { en: 'achievement', zh: '成就' },
    { en: 'responsibility', zh: '责任' },
    { en: 'relationship', zh: '关系' },
    { en: 'communication', zh: '交流' },
    { en: 'cooperation', zh: '合作' },
    { en: 'competition', zh: '竞争' },
    { en: 'imagination', zh: '想象力' },
    { en: 'inspiration', zh: '灵感' },
    { en: 'motivation', zh: '动力' },
    { en: 'determination', zh: '决心' },
    { en: 'perseverance', zh: '毅力' },
    { en: 'generosity', zh: '慷慨' },
    { en: 'gratitude', zh: '感激' },
    { en: 'curiosity', zh: '好奇心' },
    { en: 'independence', zh: '独立' },
    { en: 'confidence', zh: '自信' },
    { en: 'flexibility', zh: '灵活性' },
    { en: 'diversity', zh: '多样性' },
    { en: 'equality', zh: '平等' },
    { en: 'justice', zh: '正义' },
    { en: 'freedom', zh: '自由' },
    { en: 'democracy', zh: '民主' },
    { en: 'sustainable', zh: '可持续的' },
    { en: 'environment', zh: '环境' },
    { en: 'influence', zh: '影响' },
    { en: 'strategy', zh: '策略' },
    { en: 'evidence', zh: '证据' },
    { en: 'attitude', zh: '态度' }
  ]
};

const GRAMMAR = {
  easy: [
    { prompt: 'I ___ a student.', options: ['am', 'is', 'are', 'be'], answer: 'am' },
    { prompt: 'She ___ my sister.', options: ['is', 'am', 'are', 'be'], answer: 'is' },
    { prompt: 'They ___ playing football.', options: ['are', 'is', 'am', 'be'], answer: 'are' },
    { prompt: 'He ___ to school every day.', options: ['goes', 'go', 'going', 'gone'], answer: 'goes' },
    { prompt: 'I have ___ apple.', options: ['an', 'a', 'the', 'this'], answer: 'an' },
    { prompt: 'This is ___ book.', options: ['a', 'an', 'the', 'that'], answer: 'a' },
    { prompt: '___ is my father.', options: ['He', 'She', 'It', 'They'], answer: 'He' },
    { prompt: 'There ___ a cat under the desk.', options: ['is', 'are', 'am', 'be'], answer: 'is' },
    { prompt: '___ you like music?', options: ['Do', 'Does', 'Are', 'Is'], answer: 'Do' },
    { prompt: 'She ___ like coffee.', options: ["doesn't", "don't", "isn't", "aren't"], answer: "doesn't" },
    { prompt: 'I can ___ English.', options: ['speak', 'speaks', 'speaking', 'spoke'], answer: 'speak' },
    { prompt: 'We are ___ TV now.', options: ['watching', 'watch', 'watches', 'watched'], answer: 'watching' },
    { prompt: 'Look! The bird ___ in the sky.', options: ['is flying', 'flies', 'flew', 'fly'], answer: 'is flying' },
    { prompt: 'Tom ___ basketball yesterday.', options: ['played', 'plays', 'play', 'playing'], answer: 'played' },
    { prompt: 'It is ___ than yesterday.', options: ['hotter', 'hot', 'hottest', 'more hot'], answer: 'hotter' },
    { prompt: '___ many books are there?', options: ['How', 'What', 'Who', 'Where'], answer: 'How' },
    { prompt: 'The cat is ___ the box.', options: ['in', 'on', 'to', 'at'], answer: 'in' },
    { prompt: 'There are two ___ on the desk.', options: ['pens', 'pen', 'a pen', 'the pen'], answer: 'pens' },
    { prompt: 'I ___ up at six every morning.', options: ['get', 'gets', 'got', 'getting'], answer: 'get' },
    { prompt: 'Please ___ the window.', options: ['open', 'opens', 'opened', 'opening'], answer: 'open' }
  ],
  medium: [
    { prompt: 'She has studied English ___ 2019.', options: ['since', 'for', 'from', 'in'], answer: 'since' },
    { prompt: 'If it ___ tomorrow, we will stay at home.', options: ['rains', 'rain', 'will rain', 'rained'], answer: 'rains' },
    { prompt: 'The movie is ___ interesting that I want to see it again.', options: ['so', 'such', 'very', 'too'], answer: 'so' },
    { prompt: 'I have lived here ___ ten years.', options: ['for', 'since', 'from', 'at'], answer: 'for' },
    { prompt: 'He is interested ___ science.', options: ['in', 'on', 'at', 'with'], answer: 'in' },
    { prompt: 'My father asked me ___ the door.', options: ['to open', 'open', 'opening', 'opened'], answer: 'to open' },
    { prompt: 'This is the book ___ I bought yesterday.', options: ['that', 'who', 'what', 'where'], answer: 'that' },
    { prompt: 'The man ___ is talking to my teacher is my uncle.', options: ['who', 'which', 'what', 'whom'], answer: 'who' },
    { prompt: '___ he was tired, he kept working.', options: ['Although', 'Because', 'So', 'But'], answer: 'Although' },
    { prompt: 'English ___ by many people in the world.', options: ['is spoken', 'speaks', 'spoke', 'is speaking'], answer: 'is spoken' },
    { prompt: "You'd better ___ too much junk food.", options: ['not eat', 'not to eat', "don't eat", 'eating'], answer: 'not eat' },
    { prompt: 'Neither Tom nor his parents ___ at home.', options: ['are', 'is', 'am', 'be'], answer: 'are' },
    { prompt: 'The number of students in our class ___ 50.', options: ['is', 'are', 'am', 'be'], answer: 'is' },
    { prompt: 'I don\'t know ___ he will come tomorrow.', options: ['whether', 'what', 'that', 'which'], answer: 'whether' },
    { prompt: 'She is used to ___ early.', options: ['getting up', 'get up', 'got up', 'gets up'], answer: 'getting up' },
    { prompt: '___ wonderful the film is!', options: ['How', 'What', 'What a', 'So'], answer: 'How' },
    { prompt: 'We ___ each other since primary school.', options: ['have known', 'know', 'knew', 'are knowing'], answer: 'have known' },
    { prompt: 'The classroom ___ every day.', options: ['is cleaned', 'cleans', 'cleaned', 'is cleaning'], answer: 'is cleaned' },
    { prompt: 'He runs ___ fast ___ nobody can catch him.', options: ['so...that', 'such...that', 'too...to', 'very...that'], answer: 'so...that' },
    { prompt: 'By the time I arrived, the train ___.', options: ['had left', 'left', 'has left', 'leaves'], answer: 'had left' }
  ],
  hard: [
    { prompt: '___ is known to all, the earth goes around the sun.', options: ['As', 'What', 'It', 'Which'], answer: 'As' },
    { prompt: 'Only when the war was over ___ return to his hometown.', options: ['was he able to', 'he was able to', 'able was he to', 'he could able'], answer: 'was he able to' },
    { prompt: 'The problem is worth ___.', options: ['discussing', 'to discuss', 'discussed', 'being discussed'], answer: 'discussing' },
    { prompt: 'He is said ___ abroad last year.', options: ['to have gone', 'to go', 'going', 'to be going'], answer: 'to have gone' },
    { prompt: '___ the bad weather, the flight was delayed.', options: ['Due to', 'Because', 'Since', 'As'], answer: 'Due to' },
    { prompt: 'It was in the park ___ I met her yesterday.', options: ['that', 'where', 'which', 'when'], answer: 'that' },
    { prompt: 'Not until midnight ___ his homework.', options: ['did he finish', 'he finished', 'he did finish', 'finished he'], answer: 'did he finish' },
    { prompt: 'The young man, ___ was lost in thought, didn\'t notice me.', options: ['who', 'which', 'whom', 'whose'], answer: 'who' },
    { prompt: 'I would rather you ___ tomorrow.', options: ['came', 'come', 'will come', 'would come'], answer: 'came' },
    { prompt: 'Hardly ___ the station when the train left.', options: ['had I reached', 'I had reached', 'did I reach', 'I reached'], answer: 'had I reached' },
    { prompt: 'The teacher insisted that every student ___ on time.', options: ['be', 'is', 'was', 'were'], answer: 'be' },
    { prompt: '___ to the left, and you\'ll see the post office.', options: ['Turn', 'Turning', 'To turn', 'Turned'], answer: 'Turn' },
    { prompt: 'So fast ___ that we could hardly follow him.', options: ['did he speak', 'he spoke', 'he did speak', 'spoke he'], answer: 'did he speak' },
    { prompt: 'There is no doubt ___ he will succeed.', options: ['that', 'whether', 'if', 'what'], answer: 'that' },
    { prompt: 'The building ___ next year will be the tallest in the city.', options: ['to be built', 'built', 'being built', 'having built'], answer: 'to be built' },
    { prompt: '___ student in our class has a dictionary.', options: ['Each', 'Both', 'All', 'None'], answer: 'Each' },
    { prompt: 'The suggestion that the meeting ___ has been accepted.', options: ['be put off', 'puts off', 'is put off', 'put off'], answer: 'be put off' },
    { prompt: 'With all the work ___, he went home happily.', options: ['done', 'doing', 'to do', 'having done'], answer: 'done' },
    { prompt: 'It\'s high time that we ___ action to protect the earth.', options: ['took', 'take', 'will take', 'are taking'], answer: 'took' },
    { prompt: 'The house, ___ windows face south, is my uncle\'s.', options: ['whose', 'which', 'that', 'of which'], answer: 'whose' }
  ]
};
