'use strict';

/* ============================================================
   题库数据
   词汇格式：{ en: 'apple', zh: '苹果' }
   语法格式：{ prompt: 'I ___ a student.', options: [...], answer: 'am' }
   可自由增删；distractor 会从同难度题库中随机抽取。
   ============================================================ */

const VOCAB = {
  easy: [
    { en: 'apple', zh: '苹果' },
    { en: 'banana', zh: '香蕉' },
    { en: 'orange', zh: '橙子' },
    { en: 'grape', zh: '葡萄' },
    { en: 'watermelon', zh: '西瓜' },
    { en: 'strawberry', zh: '草莓' },
    { en: 'dog', zh: '狗' },
    { en: 'cat', zh: '猫' },
    { en: 'bird', zh: '鸟' },
    { en: 'fish', zh: '鱼' },
    { en: 'rabbit', zh: '兔子' },
    { en: 'tiger', zh: '老虎' },
    { en: 'lion', zh: '狮子' },
    { en: 'elephant', zh: '大象' },
    { en: 'panda', zh: '熊猫' },
    { en: 'book', zh: '书' },
    { en: 'pen', zh: '钢笔' },
    { en: 'desk', zh: '书桌' },
    { en: 'chair', zh: '椅子' },
    { en: 'pencil', zh: '铅笔' },
    { en: 'ruler', zh: '尺子' },
    { en: 'bag', zh: '书包' },
    { en: 'red', zh: '红色的' },
    { en: 'blue', zh: '蓝色的' },
    { en: 'green', zh: '绿色的' },
    { en: 'yellow', zh: '黄色的' },
    { en: 'white', zh: '白色的' },
    { en: 'black', zh: '黑色的' },
    { en: 'big', zh: '大的' },
    { en: 'small', zh: '小的' },
    { en: 'tall', zh: '高的' },
    { en: 'short', zh: '矮的' },
    { en: 'long', zh: '长的' },
    { en: 'run', zh: '跑' },
    { en: 'jump', zh: '跳' },
    { en: 'swim', zh: '游泳' },
    { en: 'walk', zh: '走路' },
    { en: 'sing', zh: '唱歌' },
    { en: 'dance', zh: '跳舞' },
    { en: 'mother', zh: '妈妈' },
    { en: 'father', zh: '爸爸' },
    { en: 'brother', zh: '哥哥；弟弟' },
    { en: 'sister', zh: '姐姐；妹妹' },
    { en: 'family', zh: '家庭' },
    { en: 'friend', zh: '朋友' },
    { en: 'school', zh: '学校' },
    { en: 'teacher', zh: '老师' },
    { en: 'student', zh: '学生' },
    { en: 'classroom', zh: '教室' },
    { en: 'water', zh: '水' },
    { en: 'bread', zh: '面包' },
    { en: 'milk', zh: '牛奶' },
    { en: 'egg', zh: '鸡蛋' },
    { en: 'rice', zh: '米饭' },
    { en: 'happy', zh: '高兴的' },
    { en: 'sad', zh: '伤心的' },
    { en: 'angry', zh: '生气的' },
    { en: 'tired', zh: '疲倦的' },
    { en: 'morning', zh: '早晨' },
    { en: 'afternoon', zh: '下午' },
    { en: 'evening', zh: '傍晚' },
    { en: 'night', zh: '夜晚' },
    { en: 'hand', zh: '手' },
    { en: 'head', zh: '头' },
    { en: 'eye', zh: '眼睛' },
    { en: 'ear', zh: '耳朵' },
    { en: 'mouth', zh: '嘴巴' },
    { en: 'door', zh: '门' },
    { en: 'window', zh: '窗户' },
    { en: 'wall', zh: '墙' },
    { en: 'floor', zh: '地板' },
    { en: 'sun', zh: '太阳' },
    { en: 'moon', zh: '月亮' },
    { en: 'star', zh: '星星' },
    { en: 'cloud', zh: '云' },
    { en: 'rain', zh: '雨' },
    { en: 'snow', zh: '雪' },
    { en: 'car', zh: '小汽车' },
    { en: 'bus', zh: '公共汽车' },
    { en: 'bike', zh: '自行车' },
    { en: 'train', zh: '火车' },
    { en: 'plane', zh: '飞机' },
    { en: 'ship', zh: '轮船' },
  ],
  medium: [
    { en: 'environment', zh: '环境' },
    { en: 'pollution', zh: '污染' },
    { en: 'recycle', zh: '回收利用' },
    { en: 'protect', zh: '保护' },
    { en: 'ancient', zh: '古代的' },
    { en: 'modern', zh: '现代的' },
    { en: 'traditional', zh: '传统的' },
    { en: 'fashionable', zh: '时尚的' },
    { en: 'honest', zh: '诚实的' },
    { en: 'brave', zh: '勇敢的' },
    { en: 'patient', zh: '有耐心的' },
    { en: 'generous', zh: '慷慨的' },
    { en: 'achievement', zh: '成就' },
    { en: 'challenge', zh: '挑战' },
    { en: 'opportunity', zh: '机会' },
    { en: 'experience', zh: '经验；经历' },
    { en: 'communicate', zh: '交流' },
    { en: 'cooperate', zh: '合作' },
    { en: 'compete', zh: '竞争' },
    { en: 'compare', zh: '比较' },
    { en: 'increase', zh: '增加' },
    { en: 'decrease', zh: '减少' },
    { en: 'improve', zh: '改进' },
    { en: 'reduce', zh: '减少' },
    { en: 'celebrate', zh: '庆祝' },
    { en: 'decorate', zh: '装饰' },
    { en: 'encourage', zh: '鼓励' },
    { en: 'discover', zh: '发现' },
    { en: 'invent', zh: '发明' },
    { en: 'explore', zh: '探索' },
    { en: 'imagine', zh: '想象' },
    { en: 'wonder', zh: '想知道；奇迹' },
    { en: 'believe', zh: '相信' },
    { en: 'achieve', zh: '实现；达到' },
    { en: 'succeed', zh: '成功' },
    { en: 'fail', zh: '失败' },
    { en: 'borrow', zh: '借入' },
    { en: 'lend', zh: '借出' },
    { en: 'suggest', zh: '建议' },
    { en: 'advise', zh: '劝告' },
    { en: 'promise', zh: '承诺' },
    { en: 'refuse', zh: '拒绝' },
    { en: 'accept', zh: '接受' },
    { en: 'explain', zh: '解释' },
    { en: 'describe', zh: '描述' },
    { en: 'foreign', zh: '外国的' },
    { en: 'local', zh: '当地的' },
    { en: 'private', zh: '私人的' },
    { en: 'public', zh: '公共的' },
    { en: 'wealthy', zh: '富有的' },
    { en: 'terrible', zh: '可怕的；糟糕的' },
    { en: 'wonderful', zh: '精彩的' },
    { en: 'excellent', zh: '优秀的' },
    { en: 'common', zh: '常见的' },
    { en: 'special', zh: '特别的' },
    { en: 'ordinary', zh: '普通的' },
    { en: 'strange', zh: '奇怪的' },
    { en: 'comfortable', zh: '舒适的' },
    { en: 'convenient', zh: '方便的' },
    { en: 'difficult', zh: '困难的' },
    { en: 'dangerous', zh: '危险的' },
    { en: 'necessary', zh: '必要的' },
    { en: 'possible', zh: '可能的' },
  ],
  hard: [
    { en: 'ambiguous', zh: '模棱两可的' },
    { en: 'inevitable', zh: '不可避免的' },
    { en: 'controversial', zh: '有争议的' },
    { en: 'significant', zh: '重要的；显著的' },
    { en: 'phenomenon', zh: '现象' },
    { en: 'hypothesis', zh: '假设' },
    { en: 'theory', zh: '理论' },
    { en: 'evidence', zh: '证据' },
    { en: 'sustainable', zh: '可持续的' },
    { en: 'renewable', zh: '可再生的' },
    { en: 'efficient', zh: '高效的' },
    { en: 'sufficient', zh: '充足的' },
    { en: 'sophisticated', zh: '复杂精密的' },
    { en: 'innovative', zh: '创新的' },
    { en: 'feasible', zh: '可行的' },
    { en: 'rigorous', zh: '严格的' },
    { en: 'comprehensive', zh: '全面的' },
    { en: 'fundamental', zh: '根本的；基础的' },
    { en: 'potential', zh: '潜在的；潜力' },
    { en: 'priority', zh: '优先事项' },
    { en: 'crisis', zh: '危机' },
    { en: 'strategy', zh: '策略' },
    { en: 'obstacle', zh: '障碍' },
    { en: 'consequence', zh: '后果' },
    { en: 'circumstance', zh: '环境；情况' },
    { en: 'contemporary', zh: '当代的' },
    { en: 'extraordinary', zh: '非凡的' },
    { en: 'remarkable', zh: '显著的；非凡的' },
    { en: 'crucial', zh: '至关重要的' },
    { en: 'vital', zh: '至关重要的' },
    { en: 'obscure', zh: '晦涩的；模糊的' },
    { en: 'profound', zh: '深刻的' },
    { en: 'subtle', zh: '微妙的' },
    { en: 'tremendous', zh: '巨大的' },
    { en: 'acknowledge', zh: '承认；致谢' },
    { en: 'advocate', zh: '提倡；拥护' },
    { en: 'anticipate', zh: '预期；预料' },
    { en: 'compensate', zh: '补偿' },
    { en: 'contradict', zh: '反驳；矛盾' },
    { en: 'demonstrate', zh: '证明；演示' },
    { en: 'distinguish', zh: '区分；辨别' },
    { en: 'eliminate', zh: '消除' },
    { en: 'emphasize', zh: '强调' },
    { en: 'evaluate', zh: '评估' },
    { en: 'exaggerate', zh: '夸大' },
    { en: 'facilitate', zh: '促进；使便利' },
    { en: 'implement', zh: '实施' },
    { en: 'integrate', zh: '整合' },
    { en: 'negotiate', zh: '谈判' },
    { en: 'overcome', zh: '克服' },
  ],
};

const GRAMMAR = {
  easy: [
    { prompt: 'I ___ a student.', options: ['am', 'is', 'are', 'be'], answer: 'am' },
    { prompt: 'She ___ to school every day.', options: ['go', 'goes', 'going', 'gone'], answer: 'goes' },
    { prompt: '___ you like apples?', options: ['Do', 'Does', 'Are', 'Is'], answer: 'Do' },
    { prompt: 'There ___ a book on the desk.', options: ['is', 'are', 'am', 'be'], answer: 'is' },
    { prompt: 'I have ___ apple.', options: ['a', 'an', 'the', 'one'], answer: 'an' },
    { prompt: 'He is ___ than his brother.', options: ['tall', 'taller', 'tallest', 'more tall'], answer: 'taller' },
    { prompt: 'This is ___ book.', options: ['my', 'I', 'me', 'mine'], answer: 'my' },
    { prompt: 'They ___ playing football now.', options: ['is', 'am', 'are', 'be'], answer: 'are' },
    { prompt: 'I ___ TV yesterday evening.', options: ['watch', 'watched', 'watching', 'watches'], answer: 'watched' },
    { prompt: 'Tom is the ___ boy in his class.', options: ['tall', 'taller', 'tallest', 'more tall'], answer: 'tallest' },
    { prompt: '___ is your name?', options: ['What', 'Who', 'When', 'Why'], answer: 'What' },
    { prompt: 'Can you ___ me?', options: ['help', 'helps', 'helped', 'helping'], answer: 'help' },
    { prompt: 'She has two ___.', options: ['child', 'childs', 'children', 'childrens'], answer: 'children' },
    { prompt: 'I get up ___ 6 o\'clock.', options: ['in', 'on', 'at', 'for'], answer: 'at' },
    { prompt: 'We go to school ___ Monday.', options: ['in', 'on', 'at', 'of'], answer: 'on' },
    { prompt: 'Look! The birds ___ in the sky.', options: ['fly', 'flying', 'are flying', 'flew'], answer: 'are flying' },
    { prompt: 'He ___ from China.', options: ['come', 'comes', 'coming', 'came'], answer: 'comes' },
    { prompt: '___ many students in the classroom.', options: ['There is', 'There are', 'They are', 'It is'], answer: 'There are' },
    { prompt: 'My birthday is ___ May.', options: ['in', 'on', 'at', 'of'], answer: 'in' },
    { prompt: 'This pen is ___.', options: ['I', 'me', 'my', 'mine'], answer: 'mine' },
    { prompt: 'She is good ___ English.', options: ['in', 'at', 'on', 'for'], answer: 'at' },
    { prompt: 'How ___ apples do you want?', options: ['many', 'much', 'old', 'long'], answer: 'many' },
    { prompt: 'I want ___ water.', options: ['some', 'any', 'many', 'a few'], answer: 'some' },
    { prompt: 'He doesn\'t ___ coffee.', options: ['like', 'likes', 'liking', 'liked'], answer: 'like' },
    { prompt: 'Let\'s ___ a game!', options: ['play', 'plays', 'playing', 'played'], answer: 'play' },
    { prompt: 'The cat is ___ the box.', options: ['in', 'on', 'at', 'for'], answer: 'in' },
    { prompt: 'What ___ you doing?', options: ['is', 'am', 'are', 'be'], answer: 'are' },
    { prompt: 'I can ___ English very well.', options: ['speak', 'speaks', 'speaking', 'spoke'], answer: 'speak' },
    { prompt: 'These are my ___.', options: ['friend', 'friends', 'friend\'s', 'friends\'s'], answer: 'friends' },
    { prompt: '___ is the weather like today?', options: ['What', 'How', 'Who', 'When'], answer: 'What' },
  ],
  medium: [
    { prompt: 'If it ___ tomorrow, we will stay at home.', options: ['rain', 'rains', 'rained', 'raining'], answer: 'rains' },
    { prompt: 'I have lived here ___ 2010.', options: ['for', 'since', 'from', 'in'], answer: 'since' },
    { prompt: 'The book ___ by Mark Twain is interesting.', options: ['write', 'wrote', 'written', 'writing'], answer: 'written' },
    { prompt: 'You\'d better ___ to bed early.', options: ['go', 'to go', 'going', 'gone'], answer: 'go' },
    { prompt: 'The number of students ___ increasing.', options: ['is', 'are', 'am', 'be'], answer: 'is' },
    { prompt: 'He asked me where I ___.', options: ['live', 'lived', 'living', 'lives'], answer: 'lived' },
    { prompt: 'Not only Tom but also his parents ___ here.', options: ['is', 'are', 'was', 'be'], answer: 'are' },
    { prompt: 'This is the house ___ I grew up.', options: ['where', 'which', 'what', 'who'], answer: 'where' },
    { prompt: 'I look forward to ___ from you.', options: ['hear', 'hearing', 'heard', 'hears'], answer: 'hearing' },
    { prompt: 'By the time we arrived, the train ___.', options: ['left', 'has left', 'had left', 'leaves'], answer: 'had left' },
    { prompt: 'The harder you work, ___ progress you will make.', options: ['the more', 'more', 'the most', 'most'], answer: 'the more' },
    { prompt: 'She suggested ___ a picnic this weekend.', options: ['having', 'to have', 'have', 'had'], answer: 'having' },
    { prompt: 'The story ___ by my grandma touched me.', options: ['tell', 'told', 'telling', 'tells'], answer: 'told' },
    { prompt: 'He is used to ___ up early.', options: ['get', 'getting', 'got', 'gets'], answer: 'getting' },
    { prompt: 'We ___ each other since childhood.', options: ['know', 'knew', 'have known', 'knowing'], answer: 'have known' },
    { prompt: 'I don\'t know ___ he will come.', options: ['if', 'what', 'which', 'who'], answer: 'if' },
    { prompt: 'This is the most interesting film I ___.', options: ['see', 'saw', 'have seen', 'seen'], answer: 'have seen' },
    { prompt: 'The meeting ___ when I arrived.', options: ['started', 'has started', 'had started', 'starts'], answer: 'had started' },
    { prompt: 'He devoted himself ___ science.', options: ['to', 'for', 'in', 'on'], answer: 'to' },
    { prompt: '___ from the hill, the city looks beautiful.', options: ['See', 'Seeing', 'Seen', 'To see'], answer: 'Seen' },
    { prompt: 'I prefer tea ___ coffee.', options: ['to', 'than', 'over', 'against'], answer: 'to' },
    { prompt: 'Neither he nor I ___ wrong.', options: ['is', 'am', 'are', 'be'], answer: 'am' },
    { prompt: 'The weather is getting ___.', options: ['warm and warm', 'warmer and warmer', 'warmest', 'more warm'], answer: 'warmer and warmer' },
    { prompt: 'It is important ___ English well.', options: ['learn', 'learning', 'to learn', 'learned'], answer: 'to learn' },
    { prompt: 'A new hospital ___ in our city next year.', options: ['builds', 'will build', 'will be built', 'is building'], answer: 'will be built' },
    { prompt: 'She is the girl ___ won the first prize.', options: ['which', 'who', 'whom', 'what'], answer: 'who' },
    { prompt: 'I spent two hours ___ my homework.', options: ['do', 'doing', 'to do', 'done'], answer: 'doing' },
    { prompt: 'He speaks English as ___ as his teacher.', options: ['good', 'well', 'better', 'best'], answer: 'well' },
    { prompt: 'Hurry up, ___ you will miss the bus.', options: ['and', 'or', 'but', 'so'], answer: 'or' },
    { prompt: 'The price of these shoes ___ reasonable.', options: ['is', 'are', 'has', 'have'], answer: 'is' },
  ],
  hard: [
    { prompt: 'Had he studied harder, he ___ the exam.', options: ['would pass', 'would have passed', 'passed', 'has passed'], answer: 'would have passed' },
    { prompt: 'Not until midnight ___ home.', options: ['he returned', 'did he return', 'he had returned', 'had he returned'], answer: 'did he return' },
    { prompt: 'It\'s high time we ___ action.', options: ['take', 'took', 'taken', 'to take'], answer: 'took' },
    { prompt: '___ no doubt that he is honest.', options: ['There is', 'It is', 'That is', 'What is'], answer: 'There is' },
    { prompt: 'He was accused ___ cheating in the exam.', options: ['of', 'for', 'with', 'about'], answer: 'of' },
    { prompt: 'Seldom ___ such a beautiful sight.', options: ['I have seen', 'have I seen', 'I saw', 'did I saw'], answer: 'have I seen' },
    { prompt: 'The project, ___ by the team, won the prize.', options: ['design', 'designed', 'designing', 'to design'], answer: 'designed' },
    { prompt: 'I\'d rather you ___ here with me.', options: ['stay', 'stayed', 'staying', 'to stay'], answer: 'stayed' },
    { prompt: 'The news ___ encouraging.', options: ['is', 'are', 'has', 'have'], answer: 'is' },
    { prompt: 'But for your help, I ___ the game.', options: ['would lose', 'would have lost', 'lost', 'have lost'], answer: 'would have lost' },
    { prompt: 'He is believed ___ the prize last year.', options: ['to win', 'to have won', 'winning', 'won'], answer: 'to have won' },
    { prompt: '___ he comes or not doesn\'t matter.', options: ['If', 'Whether', 'That', 'What'], answer: 'Whether' },
    { prompt: 'The theory proved ___ correct.', options: ['to be', 'being', 'be', 'been'], answer: 'to be' },
    { prompt: 'So fast ___ that we couldn\'t see him.', options: ['he ran', 'did he run', 'he runs', 'was he running'], answer: 'did he run' },
    { prompt: 'The population of China is larger than ___ of Japan.', options: ['it', 'this', 'that', 'one'], answer: 'that' },
    { prompt: 'Never before ___ such great progress.', options: ['she has made', 'has she made', 'she made', 'she makes'], answer: 'has she made' },
    { prompt: 'It was in the park ___ I met her.', options: ['where', 'which', 'that', 'when'], answer: 'that' },
    { prompt: 'He insisted that he ___ right.', options: ['is', 'was', 'be', 'would be'], answer: 'was' },
    { prompt: 'The little girl stood there, ___.', options: ['tremble', 'trembled', 'trembling', 'to tremble'], answer: 'trembling' },
    { prompt: 'Only by working hard ___ succeed.', options: ['you can', 'can you', 'you could', 'could you'], answer: 'can you' },
    { prompt: 'My suggestion is that we ___ the plan.', options: ['carry out', 'carried out', 'carrying out', 'to carry out'], answer: 'carry out' },
    { prompt: 'He narrowly escaped ___ in the accident.', options: ['killed', 'being killed', 'killing', 'to be killed'], answer: 'being killed' },
    { prompt: '___ the exam, he felt relieved.', options: ['Passing', 'Passed', 'Having passed', 'To pass'], answer: 'Having passed' },
    { prompt: 'The furniture in the room ___ brand new.', options: ['is', 'are', 'has', 'have'], answer: 'is' },
    { prompt: 'A number of students ___ playing on the playground.', options: ['is', 'are', 'was', 'has'], answer: 'are' },
    { prompt: 'It is the first time that I ___ this movie.', options: ['see', 'saw', 'have seen', 'had seen'], answer: 'have seen' },
    { prompt: 'We insisted that he ___ to hospital at once.', options: ['sent', 'be sent', 'was sent', 'sends'], answer: 'be sent' },
    { prompt: 'His failure was due to ___ confidence.', options: ['lack of', 'lacking', 'lacked', 'lacking of'], answer: 'lack of' },
    { prompt: 'Little ___ that his dream would come true.', options: ['he expected', 'did he expect', 'he expects', 'does he expect'], answer: 'did he expect' },
    { prompt: 'On no account ___ give up our dreams.', options: ['we should', 'should we', 'we would', 'would we'], answer: 'should we' },
  ],
};
