extends SceneTree
# Godot's production Tween functions author the CSS reward animation offline.
# Runtime remains tiny native web code; no engine/WASM dependency is shipped.
func _initialize():
 var samples: Array = []
 var css = "/* Generated by Godot 4.6 tools/mobile-art/export_motion.gd. */\n@keyframes mastery-reveal {\n"
 for i in range(21):
  var t = float(i) / 20.0
  var scale_value = Tween.interpolate_value(0.66, 0.34, t, 1.0, Tween.TRANS_BACK, Tween.EASE_OUT)
  var rise = Tween.interpolate_value(12.0, -12.0, t, 1.0, Tween.TRANS_CUBIC, Tween.EASE_OUT)
  samples.append({"t":t,"scale":scale_value,"y":rise})
  css += "  %s%% { transform: translateY(%.4fpx) scale(%.5f); opacity: %.3f; }\n" % [i*5,rise,scale_value,minf(1.0,t*4.0)]
 css += "}\n.mastery-medal { animation: mastery-reveal 620ms linear both; }\n@media (prefers-reduced-motion: reduce) { .mastery-medal { animation: none; } }\n"
 var out = ProjectSettings.globalize_path("res://../../shared/mobile-art/")
 var file = FileAccess.open(out+"reward-motion.json",FileAccess.WRITE)
 file.store_string(JSON.stringify({"engine":"Godot 4.6", "durationMs":620, "samples":samples},"  "));file.close()
 file = FileAccess.open(out+"reward-motion.css",FileAccess.WRITE);file.store_string(css);file.close()
 print("Exported ",samples.size()," motion samples and CSS")
 quit()
